# Nettoyage & enrichissement des boxscores (minutes, DNP, totaux, ratios)

In [1]:
import pandas as pd
import numpy as np
import os
from datetime import datetime
from nba_api.stats.static import players

from src.config import *
from src.utils import *
from src.feature_builder import *
from src.feature_aggregation import *

#display full columns
pd.set_option('display.max_column', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_seq_items', None)
# pd.set_option('display.max_colwidth', 500)
# pd.set_option('expand_frame_repr', True)

In [2]:
#store start time of notebook
start_time = datetime.now()
print("Start time: ", start_time)

Start time:  2025-11-07 23:44:21.661166

# 🔁 Chargement des fichiers

In [3]:
boxscores_file = get_latest_file(DATA_LAST_BOXSCORES_BATCHES_MERGED_DIR)
games_file = get_latest_file(DATA_LAST_GAMES_MERGED_DIR)
df_boxscores = pd.read_csv(boxscores_file, dtype={'gameId': str})
df_games = pd.read_csv(games_file, dtype={'GAME_ID': str})

/tmp/ipykernel_1075656/1838672219.py:3: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df_boxscores = pd.read_csv(boxscores_file, dtype={'gameId': str})

In [4]:
games_file

'data/01_bronze/games/games_merged_all_seasons_2025-11-07_23-30-01.csv'

In [5]:
df_boxscores

,gameId,teamId,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage
0,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1897,Metta,World Peace,M. World Peace,metta-world-peace,F,NaN,NaN,29:20,83.3,112.3,-28.9,-28.9,0.077,1.00,6.7,0.038,0.031,0.034,6.7,0.583,0.582,0.203,95.73,95.73,60.0,0.156,0.467,0.267,0.249,0.475,0.186,0.100,0.370,2,2,4,10,17,14,13,36,2,0,0.917,0.083,0.933,0.267,0.000,0.267,0.067,0.133,0.667,0.429,0.571,0.0,0.0,0.429,0.571,7,12,0,1,0.000,1,2,0.50,1,1,2,1,3,2,1,2,15,-14.0,0.350,0.267,0.0,0.200,0.125,0.167,0.125,0.059,0.080,0.125,0.071,0.75,0.667,0.400,0.143,0.000,0.300
1,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2033,Marcus,Fizer,M. Fizer,marcus-fizer,F,NaN,NaN,37:09,90.3,101.4,-11.1,-11.1,0.087,0.50,11.8,0.111,0.128,0.120,23.5,0.300,0.368,0.181,92.38,92.38,72.0,0.043,0.475,0.217,0.223,0.477,0.297,0.156,0.361,2,4,2,6,19,14,10,42,3,0,1.000,0.000,0.750,0.000,0.000,0.250,0.250,0.250,0.750,0.333,0.667,0.0,0.0,0.333,0.667,3,10,0,0,0.000,2,2,1.00,4,5,9,2,0,0,4,2,8,-7.0,0.115,0.167,0.0,0.000,0.250,0.154,0.400,0.217,0.273,0.167,0.250,0.00,0.000,0.600,0.095,0.000,0.123
2,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1434,Dragan,Tarlac,D. Tarlac,dragan-tarlac,C,NaN,NaN,22:49,85.1,122.4,-37.3,-37.3,0.000,0.00,0.0,0.150,0.154,0.152,75.0,1.000,1.064,0.151,100.98,100.98,47.0,-0.007,0.486,0.286,0.259,0.500,0.260,0.095,0.364,0,4,0,2,16,10,19,34,0,0,1.000,0.000,0.500,0.000,0.000,0.000,0.500,0.000,0.500,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,2,2,1.00,3,4,7,0,1,0,6,5,4,-20.0,0.063,0.029,0.0,0.000,0.333,0.200,0.600,0.286,0.368,0.000,0.500,0.25,0.000,0.000,0.357,0.000,0.100
3,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2064,Khalid,El-Amin,K. El-Amin,khalid-el-amin,G,NaN,NaN,27:47,100.0,107.1,-7.1,-7.1,0.286,4.00,21.1,0.042,0.107,0.077,5.3,0.643,0.643,0.242,95.88,95.88,55.0,0.188,0.545,0.250,0.237,0.538,0.154,0.144,0.348,2,0,6,6,14,10,8,40,0,0,0.786,0.214,0.667,0.333,0.333,0.333,0.000,0.111,0.333,0.167,0.833,1.0,0.0,0.375,0.625,8,14,2,3,0.667,0,0,0.00,1,3,4,4,0,1,1,2,18,-5.0,0.364,0.318,0.5,0.375,0.000,0.000,0.143,0.200,0.182,0.444,0.077,0.00,0.167,0.000,0.200,0.000,0.327
4,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1500,Ron,Mercer,R. Mercer,ron-mercer,G,NaN,NaN,41:20,86.4,113.6,-27.2,-27.2,0.045,0.33,4.2,0.000,0.095,0.050,12.5,0.361,0.405,0.250,94.06,94.06,81.0,0.037,0.469,0.200,0.238,0.500,0.256,0.142,0.378,0,0,2,4,21,18,21,54,1,0,0.889,0.111,0.625,0.375,0.188,0.125,0.188,0.000,0.250,0.600,0.400,1.0,0.0,0.667,0.333,6,18,1,2,0.500,3,4,0.75,0,4,4,1,0,1,3,1,16,-22.0,0.214,0.277,0.2,0.200,0.333,0.308,0.000,0.174,0.121,0.071,0.158,0.00,0.167,0.143,0.043,0.000,0.229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507359,0022500182,1610612756,Phoenix,Suns,PHX,suns,1630692,Jordan,Goodwin,J. Goodwin,jordan-goodwin,NaN,NaN,NaN,10:37,63.2,160.0,-96.8,-96.8,0.000,0.00,0.0,0.063,0.000,0.043,20.0,0.000,0.000,0.192,88.22,88.22,19.0,-0.265,0.278,0.222,0.241,0.769,1.462,0.000,0.500,0,0,0,0,6,4,4,6,0,0,0.500,0.500,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,4,0,2,0.000,0,0,0.00,1,0,1,0,0,0,1,2,0,-20.0,0.000,0.222,0.0,0.200,0.000,0.000,0.250,0.000,0.143,0.000,0.200,0.00,0.000,0.000,0.222,0.000,0.000
1507360,0022500182,1610612756,Phoenix,Suns,PHX,suns,1630208,Nick,Richards,N. Richards,nick-richards,NaN,NaN,NaN,11:22,100.0,84.0,16.0,16.0,0.000,0.00,0.0,0.063,0.143,0.100,50.0,1.000,0.798,0.133,103.46,103.46,24.0,0.063,0.478,0.217,0.191,0.452,0.143,0.206,0.273,0,3,0,2,6,0,4,14,0,1,1.000,0.000,0.667,0.000,0.000,0.000,0.333,0.000,0.667,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,1,2,0.50,1,2,3,0,0,0,2,0,3,3.0,0.111,0.043,0.0,0.000,0.500,0.400,0.250,0.250,0.250,0.000,0.400,0.00,0.000,0.000,0.000,0.333,0.125
1507361,0022500182,1610612756,Phoenix,Suns,PHX,suns,1642863,Khaman,Maluach,K. Maluach,khaman-maluach,NaN,NaN,NaN,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000
1507362,0022500182,1610612756,Phoenix,Suns,PHX,suns,1642853,Rasheer,Fleming,R. Fleming,rasheer-fleming,NaN,NaN,NaN,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,1.000,0.500,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,1,1,0,0,0,0,1,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.00,0.000,0.000,1.000,0.000,0.000
1507363,0022500182,1610612756,Phoenix,Suns,PHX,suns,1628502,Nigel,Hayes-Davis,N. Hayes-Davis,nigel-hayes-davis,NaN,NaN,NaN,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000

In [6]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,22010,1.610613e+09,BOS,Boston Celtics,0021000001,2010-10-26,BOS vs. MIA,W,239,88,32,69,0.464,8,16,0.500,16,25,0.640,8,34,42,25,6,4,18,19,8.0,2010-11
1,22010,1.610613e+09,PHX,Phoenix Suns,0021000002,2010-10-26,PHX @ POR,L,239,92,36,74,0.486,9,19,0.474,11,16,0.688,7,23,30,15,3,4,19,19,-14.0,2010-11
2,22010,1.610613e+09,HOU,Houston Rockets,0021000003,2010-10-26,HOU @ LAL,L,240,110,38,91,0.418,8,20,0.400,26,28,0.929,16,37,53,25,6,7,20,25,-2.0,2010-11
3,22010,1.610613e+09,POR,Portland Trail Blazers,0021000002,2010-10-26,POR vs. PHX,W,240,106,43,93,0.462,10,20,0.500,10,15,0.667,18,30,48,31,11,2,12,22,14.0,2010-11
4,22010,1.610613e+09,MIA,Miami Heat,0021000001,2010-10-26,MIA @ BOS,L,242,80,27,74,0.365,8,20,0.400,18,25,0.720,11,28,39,15,10,6,17,21,-8.0,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64489,22025,1.610613e+09,NYK,New York Knicks,0022500175,2025-11-05,NYK vs. MIN,W,239,137,55,102,0.539,19,42,0.452,8,9,0.889,21,29,50,32,7,8,14,21,23.0,2025-26
64490,22025,1.610613e+09,DAL,Dallas Mavericks,0022500177,2025-11-05,DAL vs. NOP,L,240,99,37,89,0.416,10,32,0.313,15,20,0.750,10,34,44,18,11,7,15,15,-2.0,2025-26
64491,22025,1.610613e+09,SAC,Sacramento Kings,0022500181,2025-11-05,SAC vs. GSW,W,239,121,41,83,0.494,11,23,0.478,28,33,0.848,8,39,47,27,7,5,16,18,5.0,2025-26
64492,22025,1.610613e+09,LAC,LA Clippers,0022500182,2025-11-06,LAC @ PHX,L,241,102,35,79,0.443,10,31,0.323,22,30,0.733,11,30,41,24,8,4,15,19,-13.0,2025-26
64493,22025,1.610613e+09,PHX,Phoenix Suns,0022500182,2025-11-06,PHX vs. LAC,W,239,115,41,92,0.446,19,49,0.388,14,19,0.737,15,29,44,27,13,2,15,23,13.0,2025-26

# 🧼 Nettoyage des minutes jouées

In [7]:
def convert_minutes(val):
    if pd.isna(val) or val in ['DNP', '']:
        return 0.0
    try:
        parts = str(val).split(':')
        return int(parts[0]) + int(parts[1]) / 60 if len(parts) == 2 else float(val)
    except:
        return 0.0

df_boxscores['MINUTES_PLAYED'] = df_boxscores['minutes'].apply(convert_minutes)

# Rename gameId and teamId in boxscores

In [8]:
rename_columns = {
    'gameId': 'GAME_ID',
    'teamId': 'TEAM_ID',
}

df_boxscores.rename(columns=rename_columns, inplace=True)

In [9]:
# cast 'GAME_ID', 'TEAM_ID' to string
df_games['GAME_ID'] = df_games['GAME_ID'].astype(str)
df_games['TEAM_ID'] = df_games['TEAM_ID'].astype(str)

df_boxscores['GAME_ID'] = df_boxscores['GAME_ID'].astype(str)
df_boxscores['TEAM_ID'] = df_boxscores['TEAM_ID'].astype(str)

In [10]:
print(df_games.dtypes)

SEASON_ID              int64
TEAM_ID               object
TEAM_ABBREVIATION     object
TEAM_NAME             object
GAME_ID               object
GAME_DATE             object
MATCHUP               object
WL                    object
MIN                    int64
PTS                    int64
FGM                    int64
FGA                    int64
FG_PCT               float64
FG3M                   int64
FG3A                   int64
FG3_PCT              float64
FTM                    int64
FTA                    int64
FT_PCT               float64
OREB                   int64
DREB                   int64
REB                    int64
AST                    int64
STL                    int64
BLK                    int64
TOV                    int64
PF                     int64
PLUS_MINUS           float64
SEASON                object
dtype: object

In [11]:
print(df_boxscores.dtypes)

GAME_ID                                object
TEAM_ID                                object
teamCity                               object
teamName                               object
teamTricode                            object
                                       ...
percentageBlocksAllowed_usage         float64
percentagePersonalFouls_usage         float64
percentagePersonalFoulsDrawn_usage    float64
percentagePoints_usage                float64
MINUTES_PLAYED                        float64
Length: 101, dtype: object

# Merge GAME_DATE dans les boxscores et remove les duplicates créés

In [12]:
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])
df_boxscores = df_boxscores.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

df_boxscores = df_boxscores.drop_duplicates(subset=['GAME_ID', 'TEAM_ID', 'playerSlug'])

In [13]:
# display nat GAME_DATE in df_boxscores
# check for NaT values in GAME_DATE
nat_dates = df_boxscores[df_boxscores['GAME_DATE'].isna()]
nat_dates

,GAME_ID,TEAM_ID,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,MINUTES_PLAYED,GAME_DATE
0,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1897,Metta,World Peace,M. World Peace,metta-world-peace,F,NaN,NaN,29:20,83.3,112.3,-28.9,-28.9,0.077,1.00,6.7,0.038,0.031,0.034,6.7,0.583,0.582,0.203,95.73,95.73,60.0,0.156,0.467,0.267,0.249,0.475,0.186,0.100,0.370,2,2,4,10,17,14,13,36,2,0,0.917,0.083,0.933,0.267,0.000,0.267,0.067,0.133,0.667,0.429,0.571,0.0,0.0,0.429,0.571,7,12,0,1,0.000,1,2,0.50,1,1,2,1,3,2,1,2,15,-14.0,0.350,0.267,0.0,0.200,0.125,0.167,0.125,0.059,0.080,0.125,0.071,0.75,0.667,0.400,0.143,0.000,0.300,29.333333,NaT
1,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2033,Marcus,Fizer,M. Fizer,marcus-fizer,F,NaN,NaN,37:09,90.3,101.4,-11.1,-11.1,0.087,0.50,11.8,0.111,0.128,0.120,23.5,0.300,0.368,0.181,92.38,92.38,72.0,0.043,0.475,0.217,0.223,0.477,0.297,0.156,0.361,2,4,2,6,19,14,10,42,3,0,1.000,0.000,0.750,0.000,0.000,0.250,0.250,0.250,0.750,0.333,0.667,0.0,0.0,0.333,0.667,3,10,0,0,0.000,2,2,1.00,4,5,9,2,0,0,4,2,8,-7.0,0.115,0.167,0.0,0.000,0.250,0.154,0.400,0.217,0.273,0.167,0.250,0.00,0.000,0.600,0.095,0.000,0.123,37.150000,NaT
2,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1434,Dragan,Tarlac,D. Tarlac,dragan-tarlac,C,NaN,NaN,22:49,85.1,122.4,-37.3,-37.3,0.000,0.00,0.0,0.150,0.154,0.152,75.0,1.000,1.064,0.151,100.98,100.98,47.0,-0.007,0.486,0.286,0.259,0.500,0.260,0.095,0.364,0,4,0,2,16,10,19,34,0,0,1.000,0.000,0.500,0.000,0.000,0.000,0.500,0.000,0.500,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,2,2,1.00,3,4,7,0,1,0,6,5,4,-20.0,0.063,0.029,0.0,0.000,0.333,0.200,0.600,0.286,0.368,0.000,0.500,0.25,0.000,0.000,0.357,0.000,0.100,22.816667,NaT
3,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2064,Khalid,El-Amin,K. El-Amin,khalid-el-amin,G,NaN,NaN,27:47,100.0,107.1,-7.1,-7.1,0.286,4.00,21.1,0.042,0.107,0.077,5.3,0.643,0.643,0.242,95.88,95.88,55.0,0.188,0.545,0.250,0.237,0.538,0.154,0.144,0.348,2,0,6,6,14,10,8,40,0,0,0.786,0.214,0.667,0.333,0.333,0.333,0.000,0.111,0.333,0.167,0.833,1.0,0.0,0.375,0.625,8,14,2,3,0.667,0,0,0.00,1,3,4,4,0,1,1,2,18,-5.0,0.364,0.318,0.5,0.375,0.000,0.000,0.143,0.200,0.182,0.444,0.077,0.00,0.167,0.000,0.200,0.000,0.327,27.783333,NaT
4,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1500,Ron,Mercer,R. Mercer,ron-mercer,G,NaN,NaN,41:20,86.4,113.6,-27.2,-27.2,0.045,0.33,4.2,0.000,0.095,0.050,12.5,0.361,0.405,0.250,94.06,94.06,81.0,0.037,0.469,0.200,0.238,0.500,0.256,0.142,0.378,0,0,2,4,21,18,21,54,1,0,0.889,0.111,0.625,0.375,0.188,0.125,0.188,0.000,0.250,0.600,0.400,1.0,0.0,0.667,0.333,6,18,1,2,0.500,3,4,0.75,0,4,4,1,0,1,3,1,16,-22.0,0.214,0.277,0.2,0.200,0.333,0.308,0.000,0.174,0.121,0.071,0.158,0.00,0.167,0.143,0.043,0.000,0.229,41.333333,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507359,0022500182,1610612756,Phoenix,Suns,PHX,suns,1630692,Jordan,Goodwin,J. Goodwin,jordan-goodwin,NaN,NaN,NaN,10:37,63.2,160.0,-96.8,-96.8,0.000,0.00,0.0,0.063,0.000,0.043,20.0,0.000,0.000,0.192,88.22,88.22,19.0,-0.265,0.278,0.222,0.241,0.769,1.462,0.000,0.500,0,0,0,0,6,4,4,6,0,0,0.500,0.500,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,4,0,2,0.000,0,0,0.00,1,0,1,0,0,0,1,2,0,-20.0,0.000,0.222,0.0,0.200,0.000,0.000,0.250,0.000,0.143,0.000,0.200,0.00,0.000,0.000,0.222,0.000,0.000,10.616667,NaT
1507360,0022500182,1610612756,Phoenix,Suns,PHX,suns,1630208,Nick,Richards,N. Richards,nick-richards,NaN,NaN,NaN,11:22,100.0,84.0,16.0,16.0,0.000,0.00,0.0,0.063,0.143,0.100,50.0,1.000,0.798,0.133,103.46,103.46,24.0,0.063,0.478,0.217,0.191,0.452,0.143,0.206,0.273,0,3,0,2,6,0,4,14,0,1,1.000,0.000,0.667,0.000,0.000,0.000,0.333,0.000,0.667,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,1,2,0.50,1,2,3,0,0,0,2,0,3,3.0,0.111,0.043,0.0,0.000,0.500,0.400,0.250,0.250,0.250,0.000,0.400,0.00,0.000,0.000,0.000,0.333,0.125,11.366667,NaT
1507361,0022500182,1610612756,Phoenix,Suns,PHX,suns,1642863,Khaman,Maluach,K. Maluach,khaman-maluach,NaN,NaN,NaN,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,1.150000,NaT
1507362,0022500182,1610612756,Phoenix,Suns,PHX,suns,1642853,Rasheer,Fleming,R. Fleming,rasheer-fleming,NaN,NaN,NaN,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,1.000,0.500,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,1,1,0,0,0,0,1,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.00,0.000,0.000,1.000,0.000,0.000,1.150000,NaT
1507363,0022500182,1610612756,Phoenix,Suns,PHX,suns,1628502,Nigel,Hayes-Davis,N. Hayes-Davis,nigel-hayes-davis,NaN,NaN,NaN,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,1.150000,NaT

In [14]:
missing = df_boxscores[df_boxscores['GAME_DATE'].isna()][['GAME_ID', 'TEAM_ID']].drop_duplicates()

print(f"Exemples de lignes avec GAME_DATE NaT:")
print(missing.head(10))

# On regarde s’ils existent dans df_games
merged_check = missing.merge(df_games[['GAME_ID', 'TEAM_ID']], on=['GAME_ID', 'TEAM_ID'], how='left', indicator=True)
print(merged_check['_merge'].value_counts())

Exemples de lignes avec GAME_DATE NaT:
        GAME_ID     TEAM_ID
0    0020000279  1610612741
12   0020000279  1610612742
24   0020000282  1610612745
36   0020000282  1610612758
48   0020000281  1610612761
60   0020000281  1610612744
72   0020000283  1610612755
84   0020000283  1610612757
96   0020000278  1610612746
108  0020000278  1610612766
_merge
left_only     63954
right_only        0
both              0
Name: count, dtype: int64

In [15]:
print("Exemples d’ID manquants dans df_games")
print(missing[~missing.set_index(['GAME_ID', 'TEAM_ID']).index.isin(df_games.set_index(['GAME_ID', 'TEAM_ID']).index)])

Exemples d’ID manquants dans df_games
            GAME_ID     TEAM_ID
0        0020000279  1610612741
12       0020000279  1610612742
24       0020000282  1610612745
36       0020000282  1610612758
48       0020000281  1610612761
...             ...         ...
1507294  0022500180  1610612757
1507309  0022500175  1610612750
1507324  0022500175  1610612752
1507338  0022500182  1610612746
1507351  0022500182  1610612756

[63954 rows x 2 columns]

# 🔄 Cast dynamique des colonnes numériques

In [16]:
numeric_cols = df_boxscores.select_dtypes(include=[np.number]).columns.tolist()
for col in numeric_cols:
    df_boxscores[col] = pd.to_numeric(df_boxscores[col], errors='coerce').fillna(0)

In [17]:
df_boxscores

,GAME_ID,TEAM_ID,teamCity,teamName,teamTricode,teamSlug,personId,firstName,familyName,nameI,playerSlug,position,comment,jerseyNum,minutes,offensiveRating_advanced,defensiveRating_advanced,estimatedNetRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,oppPointsOffTurnovers_misc,oppPointsSecondChance_misc,oppPointsFastBreak_misc,oppPointsPaint_misc,blocksAgainst_misc,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,threePointersPercentage_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,freeThrowsPercentage_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,plusMinusPoints_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,MINUTES_PLAYED,GAME_DATE
0,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1897,Metta,World Peace,M. World Peace,metta-world-peace,F,NaN,0.0,29:20,83.3,112.3,-28.9,-28.9,0.077,1.00,6.7,0.038,0.031,0.034,6.7,0.583,0.582,0.203,95.73,95.73,60.0,0.156,0.467,0.267,0.249,0.475,0.186,0.100,0.370,2,2,4,10,17,14,13,36,2,0,0.917,0.083,0.933,0.267,0.000,0.267,0.067,0.133,0.667,0.429,0.571,0.0,0.0,0.429,0.571,7,12,0,1,0.000,1,2,0.50,1,1,2,1,3,2,1,2,15,-14.0,0.350,0.267,0.0,0.200,0.125,0.167,0.125,0.059,0.080,0.125,0.071,0.75,0.667,0.400,0.143,0.000,0.300,29.333333,NaT
1,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2033,Marcus,Fizer,M. Fizer,marcus-fizer,F,NaN,0.0,37:09,90.3,101.4,-11.1,-11.1,0.087,0.50,11.8,0.111,0.128,0.120,23.5,0.300,0.368,0.181,92.38,92.38,72.0,0.043,0.475,0.217,0.223,0.477,0.297,0.156,0.361,2,4,2,6,19,14,10,42,3,0,1.000,0.000,0.750,0.000,0.000,0.250,0.250,0.250,0.750,0.333,0.667,0.0,0.0,0.333,0.667,3,10,0,0,0.000,2,2,1.00,4,5,9,2,0,0,4,2,8,-7.0,0.115,0.167,0.0,0.000,0.250,0.154,0.400,0.217,0.273,0.167,0.250,0.00,0.000,0.600,0.095,0.000,0.123,37.150000,NaT
2,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1434,Dragan,Tarlac,D. Tarlac,dragan-tarlac,C,NaN,0.0,22:49,85.1,122.4,-37.3,-37.3,0.000,0.00,0.0,0.150,0.154,0.152,75.0,1.000,1.064,0.151,100.98,100.98,47.0,-0.007,0.486,0.286,0.259,0.500,0.260,0.095,0.364,0,4,0,2,16,10,19,34,0,0,1.000,0.000,0.500,0.000,0.000,0.000,0.500,0.000,0.500,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,2,2,1.00,3,4,7,0,1,0,6,5,4,-20.0,0.063,0.029,0.0,0.000,0.333,0.200,0.600,0.286,0.368,0.000,0.500,0.25,0.000,0.000,0.357,0.000,0.100,22.816667,NaT
3,0020000279,1610612741,Chicago,Bulls,CHI,bulls,2064,Khalid,El-Amin,K. El-Amin,khalid-el-amin,G,NaN,0.0,27:47,100.0,107.1,-7.1,-7.1,0.286,4.00,21.1,0.042,0.107,0.077,5.3,0.643,0.643,0.242,95.88,95.88,55.0,0.188,0.545,0.250,0.237,0.538,0.154,0.144,0.348,2,0,6,6,14,10,8,40,0,0,0.786,0.214,0.667,0.333,0.333,0.333,0.000,0.111,0.333,0.167,0.833,1.0,0.0,0.375,0.625,8,14,2,3,0.667,0,0,0.00,1,3,4,4,0,1,1,2,18,-5.0,0.364,0.318,0.5,0.375,0.000,0.000,0.143,0.200,0.182,0.444,0.077,0.00,0.167,0.000,0.200,0.000,0.327,27.783333,NaT
4,0020000279,1610612741,Chicago,Bulls,CHI,bulls,1500,Ron,Mercer,R. Mercer,ron-mercer,G,NaN,0.0,41:20,86.4,113.6,-27.2,-27.2,0.045,0.33,4.2,0.000,0.095,0.050,12.5,0.361,0.405,0.250,94.06,94.06,81.0,0.037,0.469,0.200,0.238,0.500,0.256,0.142,0.378,0,0,2,4,21,18,21,54,1,0,0.889,0.111,0.625,0.375,0.188,0.125,0.188,0.000,0.250,0.600,0.400,1.0,0.0,0.667,0.333,6,18,1,2,0.500,3,4,0.75,0,4,4,1,0,1,3,1,16,-22.0,0.214,0.277,0.2,0.200,0.333,0.308,0.000,0.174,0.121,0.071,0.158,0.00,0.167,0.143,0.043,0.000,0.229,41.333333,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507359,0022500182,1610612756,Phoenix,Suns,PHX,suns,1630692,Jordan,Goodwin,J. Goodwin,jordan-goodwin,NaN,NaN,0.0,10:37,63.2,160.0,-96.8,-96.8,0.000,0.00,0.0,0.063,0.000,0.043,20.0,0.000,0.000,0.192,88.22,88.22,19.0,-0.265,0.278,0.222,0.241,0.769,1.462,0.000,0.500,0,0,0,0,6,4,4,6,0,0,0.500,0.500,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,4,0,2,0.000,0,0,0.00,1,0,1,0,0,0,1,2,0,-20.0,0.000,0.222,0.0,0.200,0.000,0.000,0.250,0.000,0.143,0.000,0.200,0.00,0.000,0.000,0.222,0.000,0.000,10.616667,NaT
1507360,0022500182,1610612756,Phoenix,Suns,PHX,suns,1630208,Nick,Richards,N. Richards,nick-richards,NaN,NaN,0.0,11:22,100.0,84.0,16.0,16.0,0.000,0.00,0.0,0.063,0.143,0.100,50.0,1.000,0.798,0.133,103.46,103.46,24.0,0.063,0.478,0.217,0.191,0.452,0.143,0.206,0.273,0,3,0,2,6,0,4,14,0,1,1.000,0.000,0.667,0.000,0.000,0.000,0.333,0.000,0.667,0.000,1.000,0.0,0.0,0.000,1.000,1,1,0,0,0.000,1,2,0.50,1,2,3,0,0,0,2,0,3,3.0,0.111,0.043,0.0,0.000,0.500,0.400,0.250,0.250,0.250,0.000,0.400,0.00,0.000,0.000,0.000,0.333,0.125,11.366667,NaT
1507361,0022500182,1610612756,Phoenix,Suns,PHX,suns,1642863,Khaman,Maluach,K. Maluach,khaman-maluach,NaN,NaN,0.0,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,1.150000,NaT
1507362,0022500182,1610612756,Phoenix,Suns,PHX,suns,1642853,Rasheer,Fleming,R. Fleming,rasheer-fleming,NaN,NaN,0.0,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,1.000,0.500,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,1,1,0,0,0,0,1,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,1.000,1.000,0.000,0.000,0.00,0.000,0.000,1.000,0.000,0.000,1.150000,NaT
1507363,0022500182,1610612756,Phoenix,Suns,PHX,suns,1628502,Nigel,Hayes-Davis,N. Hayes-Davis,nigel-hayes-davis,NaN,NaN,0.0,1:09,0.0,66.7,-66.7,-66.7,0.000,0.00,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.000,104.35,104.35,2.0,0.000,0.000,0.000,0.500,1.000,2.000,0.000,0.000,0,0,0,0,0,0,0,2,0,0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.000,0.000,0,0,0,0,0.000,0,0,0.00,0,0,0,0,0,0,0,0,0,-2.0,0.000,0.000,0.0,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,0.000,0.000,0.000,1.150000,NaT

# Build player features (players and top players absence for each game)

In [18]:
player_features_df = build_player_status_features(df_boxscores)

today = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')


os.makedirs(DATA_PLAYERS_DIR, exist_ok=True)
player_features_output = os.path.join(DATA_PLAYERS_DIR, f'player_features_{today}.csv')

# to csv
#player_features_df.to_csv(player_features_output, index=False)

In [19]:
player_features_df

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
0,0020000279,1610612741,NaT,1897,1,0,0,0,0,0,0,22.9,5.5,18.5,0.156,
1,0020000279,1610612741,NaT,2033,1,0,0,0,0,0,0,17.8,-2.0,8.6,0.043,
2,0020000279,1610612741,NaT,1434,1,0,0,0,0,0,0,7.4,-3.5,-1.2,-0.007,
3,0020000279,1610612741,NaT,2064,1,0,0,0,0,0,0,28.8,-0.5,26.6,0.188,
4,0020000279,1610612741,NaT,1500,1,0,0,0,0,0,0,20.3,0.5,17.7,0.037,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1507359,0022500182,1610612756,NaT,1630692,1,0,0,0,0,0,0,0.2,-2.0,-1.0,-0.265,
1507360,0022500182,1610612756,NaT,1630208,1,0,0,0,0,0,0,4.6,0.0,1.6,0.063,
1507361,0022500182,1610612756,NaT,1642863,1,0,0,0,0,0,0,0.0,0.0,0.0,0.000,
1507362,0022500182,1610612756,NaT,1642853,1,0,0,0,0,0,0,1.2,-1.0,0.0,0.000,
1507363,0022500182,1610612756,NaT,1628502,1,0,0,0,0,0,0,0.0,0.0,0.0,0.000,

In [20]:
#print duplicates on 'GAME_ID' and 'TEAM_ID', personId
duplicates = player_features_df[player_features_df.duplicated(subset=['GAME_ID', 'TEAM_ID', 'personId'], keep=False)]
if not duplicates.empty:
    print("Duplicates found:")
    display(duplicates)

In [21]:
#player_features_df[player_features_df['is_absent'] == 1].sort_values(by='GAME_ID').head(50)

#same but filter with comment "DNP - Coach's Decision"

filtered = player_features_df[
    (player_features_df['is_absent'] == 1) &
    (~player_features_df['comment'].str.contains("coach's decision", na=False))
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(10))

filtered = player_features_df[
    (player_features_df['is_personal'] == 1) &
    (~player_features_df['comment'].str.contains("personal", na=False)) &
    (~player_features_df['comment'].str.contains("not with team", na=False)) 
]
display(filtered.sort_values(by=['GAME_ID', 'TEAM_ID']).tail(10))




# display(player_features_df[
#     player_features_df['is_personal'] == 1 &
#     (~player_features_df['comment'].str.contains("nwt", na=False))
#     ].head(50))

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
1366614,0052300201,1610612741,NaT,1641763,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
1366615,0052300201,1610612741,NaT,1630172,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
1366628,0052300201,1610612748,NaT,202710,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
1366629,0052300201,1610612748,NaT,1626196,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
1366630,0052300201,1610612748,NaT,1626179,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
1435671,0052400101,1610612737,NaT,1630552,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnp - injury/illness
1435725,0052400111,1610612748,NaT,1631107,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
1435727,0052400111,1610612748,NaT,201567,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd-return to competition reconditioning
1435792,0052400201,1610612737,NaT,1630552,0,1,1,0,0,0,0,0.0,0.0,0.0,0.0,dnd - injury/illness
1435780,0052400201,1610612748,NaT,201567,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - personal

,GAME_ID,TEAM_ID,GAME_DATE,personId,is_present,is_absent,is_injured,is_resting,is_suspended,is_personal,is_absent_other,player_perf_score,player_defense_score,player_offense_score,player_impact_score,comment
645998,0021200144,1610612738,NaT,2545,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
647652,0021200607,1610612745,NaT,202962,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
673094,0021201169,1610612756,NaT,201563,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
657429,0021201182,1610612739,NaT,203079,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family matters
801619,0021400441,1610612757,NaT,2549,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family
791352,0021400871,1610612737,NaT,201143,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family reasons
83720,0040100154,1610612759,NaT,1495,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - death in family
203566,0040400311,1610612759,NaT,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business
203580,0040400312,1610612759,NaT,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business
203617,0040400313,1610612759,NaT,299,0,1,0,0,0,1,0,0.0,0.0,0.0,0.0,nwt - family business

In [22]:

# Analyse des statuts des joueurs
total_rows = len(player_features_df)

# Comptage des cas
n_present = player_features_df['is_present'].sum()
n_absent = player_features_df['is_absent'].sum()
n_injured = player_features_df['is_injured'].sum()

# is_resting
# is_suspended
# is_personal

n_resting = player_features_df['is_resting'].sum()
n_suspended = player_features_df['is_suspended'].sum()
n_personal = player_features_df['is_personal'].sum()

# Lignes incohérentes : aucune des colonnes n'est True

mask_no_status = (
    (player_features_df['is_present'] == 0) &
    (player_features_df['is_absent'] == 0) &
    (player_features_df['is_injured'] == 0) &
    (player_features_df['is_resting'] == 0) &
    (player_features_df['is_suspended'] == 0) &
    (player_features_df['is_personal'] == 0)
)


n_inconsistent = mask_no_status.sum()

# Lignes avec plusieurs statuts à la fois (logiquement impossible)
mask_multiple_status = (
    player_features_df[['is_present', 'is_absent', 'is_injured']].sum(axis=1) > 1
)
n_multiple = mask_multiple_status.sum()

print(f"✅ Analyse des statuts des joueurs sur {total_rows} lignes")
print(f" - Joueurs présents : {n_present}")
print(f" - Joueurs absents : {n_absent}")
print(f" - Joueurs blessés : {n_injured}")
print(f" - Joueurs en repos : {n_resting}")
print(f" - Joueurs suspendus : {n_suspended}")
print(f" - Joueurs pour raisons personnelles : {n_personal}")
print(f"❌ Lignes sans statut défini : {n_inconsistent}")
print(f"⚠️ Lignes avec plusieurs statuts actifs : {n_multiple}")

display(player_features_df[mask_no_status].head(10))

✅ Analyse des statuts des joueurs sur 755300 lignes
 - Joueurs présents : 619955
 - Joueurs absents : 135345
 - Joueurs blessés : 21345
 - Joueurs en repos : 392
 - Joueurs suspendus : 1039
 - Joueurs pour raisons personnelles : 1005
❌ Lignes sans statut défini : 0
⚠️ Lignes avec plusieurs statuts actifs : 21345

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, GAME_DATE, personId, is_present, is_absent, is_injured, is_resting, is_suspended, is_personal, is_absent_other, player_perf_score, player_defense_score, player_offense_score, player_impact_score, comment]
Index: []

# ⚙️ Aggrégation des data Player par équipe et match

In [23]:
# df_team_players = aggregate_team_player_features(player_features_df, top_n=10)

# display(df_team_players.head(10))
# display(df_team_players.tail(10))

# #display some lines with absent players
# absent_players = df_team_players[df_team_players['num_injured'] >= 1]
# absent_players 

# Identification des top joueurs sur l'ensemble du dataset
df_top_players = identify_historical_top_players(player_features_df)
print(f"✅ {df_top_players['is_historical_top'].sum()} top joueurs identifiés sur {len(df_top_players)} joueurs.")


df_agg_actual = aggregate_actual_team_features(player_features_df)
print(f"✅ {df_agg_actual.shape[0]} lignes générées dans l'aggregation actuelle par équipe.")

df_agg_top_abs = flag_top_players_absences(player_features_df, df_top_players)
print(f"✅ {df_agg_top_abs['top_player_absent'].sum()} absences de top joueurs détectées.")

df_team_features_final = df_agg_actual.merge(df_agg_top_abs, on=["GAME_ID", "TEAM_ID"], how="left")
df_team_features_final.fillna(0, inplace=True)

#add flags has_top_absent flag to use it as input and not roll it to see in analyse how much it helps to scrap this data before match
df_team_features_final['has_top_absent'] = df_team_features_final['top_player_absent'].apply(lambda x: 1 if x > 0 else 0)
df_team_features_final['has_absent'] = df_team_features_final['num_absent'].apply(lambda x: 1 if x > 0 else 0)


#sort by GAME_ID, TEAM_ID and GAME_DATE
df_team_features_final.sort_values(by=['GAME_ID', 'TEAM_ID', 'GAME_DATE'], inplace=True)


print(f"✅ Fusion réussie. Shape finale : {df_team_features_final.shape}")

/home/ju/Documents/Dev/NBA_Predictor/src/feature_aggregation.py:92: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tops = roll.groupby(['GAME_ID', 'TEAM_ID']).apply(pick_top).reset_index()

✅ 308495 top joueurs identifiés sur 308495 joueurs.
✅ 0 lignes générées dans l'aggregation actuelle par équipe.
✅ 22048 absences de top joueurs détectées.
✅ Fusion réussie. Shape finale : (0, 27)

In [24]:
# display(df_team_features_final.head(10))
# display(df_team_features_final.tail(10))

# top_player_absence_rate
# top_player_injury_rate
# top_player_resting_rate
# top_player_suspension_rate
# top_player_personal_rate

# display(df_team_features_final[df_team_features_final['top_player_absent_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_injury_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_resting_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_suspension_rate'] > 0])
# display(df_team_features_final[df_team_features_final['top_player_personal_rate'] > 0])
display(df_team_features_final)

Empty DataFrame
Columns: [GAME_ID, TEAM_ID, GAME_DATE, player_perf_score_mean, player_perf_score_sum, num_present, num_absent, num_injured, num_suspended, num_resting, num_personal, num_absent_other, top_player_count, top_player_absent, top_player_injured, top_player_resting, top_player_suspended, top_player_personal, top_player_absent_other, top_player_absent_rate, top_player_injury_rate, top_player_resting_rate, top_player_suspension_rate, top_player_personal_rate, top_player_absent_other_rate, has_top_absent, has_absent]
Index: []

# ⚙️ Aggrégation des data Boxscore purs par équipe et match

## 📊 Agrégation des données par équipe et match

In [25]:

# 1. Agrégation par somme
group_keys = ['GAME_ID', 'TEAM_ID']
sum_agg = df_boxscores[group_keys + cols_to_sum].copy()
sum_agg = sum_agg.groupby(group_keys).sum().reset_index()

# 2. Agrégation pondérée par les minutes jouées
weighted_agg = compute_weighted_mean_features(df_boxscores, group_keys, cols_to_weighted_avg, weight_col='MINUTES_PLAYED')

# 3. Fusion des deux agrégats
team_match_stats = pd.merge(sum_agg, weighted_agg, on=group_keys, how='left')

# 4. Identifier l'équipe adverse
teams_in_game = df_boxscores.groupby('GAME_ID')['TEAM_ID'].unique().to_dict()
def get_opponent(row):
    teams = teams_in_game.get(row['GAME_ID'], [])
    opps = [tid for tid in teams if tid != row['TEAM_ID']]
    return opps[0] if opps else None

team_match_stats['OPP_TEAM_ID'] = team_match_stats.apply(get_opponent, axis=1)

In [26]:
count = 0

for game_id, teams in teams_in_game.items():
    if len(teams) < 2:
        #print(f"Attention : GAME_ID {game_id} a moins de 2 équipes : {teams}")
        count += 1
        
print(f"Nombre de GAME_ID avec moins de 2 équipes : {count}")

Nombre de GAME_ID avec moins de 2 équipes : 392

# 🔁 Ajout des colonnes OPP_ avec les data de l'adversaire

In [27]:
team_cols = [col for col in team_match_stats.columns if col not in ['GAME_ID', 'TEAM_ID', 'OPP_TEAM_ID']]
opp_cols = [f"OPP_{col}" for col in team_cols]
df_opp = team_match_stats.rename(columns={col: f"OPP_{col}" for col in team_cols}).rename(
    columns={'TEAM_ID': 'OPP_TEAM_ID', 'OPP_TEAM_ID': 'TEAM_ID'})
match_dataset = pd.merge(
    team_match_stats,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [28]:
match_dataset.columns

Index(['GAME_ID', 'TEAM_ID', 'fieldGoalsMade_traditional',
       'fieldGoalsAttempted_traditional', 'threePointersMade_traditional',
       'threePointersAttempted_traditional', 'freeThrowsMade_traditional',
       'freeThrowsAttempted_traditional', 'reboundsOffensive_traditional',
       'reboundsDefensive_traditional',
       ...
       'OPP_percentageReboundsTotal_usage', 'OPP_percentageAssists_usage',
       'OPP_percentageTurnovers_usage', 'OPP_percentageSteals_usage',
       'OPP_percentageBlocks_usage', 'OPP_percentageBlocksAllowed_usage',
       'OPP_percentagePersonalFouls_usage',
       'OPP_percentagePersonalFoulsDrawn_usage', 'OPP_percentagePoints_usage',
       'OPP_plusMinusPoints_traditional'],
      dtype='object', length=165)

# 🏠 Ajout IS_HOME et IS_WIN

In [29]:
df_games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS,SEASON
0,22010,1610612738.0,BOS,Boston Celtics,0021000001,2010-10-26,BOS vs. MIA,W,239,88,32,69,0.464,8,16,0.500,16,25,0.640,8,34,42,25,6,4,18,19,8.0,2010-11
1,22010,1610612756.0,PHX,Phoenix Suns,0021000002,2010-10-26,PHX @ POR,L,239,92,36,74,0.486,9,19,0.474,11,16,0.688,7,23,30,15,3,4,19,19,-14.0,2010-11
2,22010,1610612745.0,HOU,Houston Rockets,0021000003,2010-10-26,HOU @ LAL,L,240,110,38,91,0.418,8,20,0.400,26,28,0.929,16,37,53,25,6,7,20,25,-2.0,2010-11
3,22010,1610612757.0,POR,Portland Trail Blazers,0021000002,2010-10-26,POR vs. PHX,W,240,106,43,93,0.462,10,20,0.500,10,15,0.667,18,30,48,31,11,2,12,22,14.0,2010-11
4,22010,1610612748.0,MIA,Miami Heat,0021000001,2010-10-26,MIA @ BOS,L,242,80,27,74,0.365,8,20,0.400,18,25,0.720,11,28,39,15,10,6,17,21,-8.0,2010-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64489,22025,1610612752.0,NYK,New York Knicks,0022500175,2025-11-05,NYK vs. MIN,W,239,137,55,102,0.539,19,42,0.452,8,9,0.889,21,29,50,32,7,8,14,21,23.0,2025-26
64490,22025,1610612742.0,DAL,Dallas Mavericks,0022500177,2025-11-05,DAL vs. NOP,L,240,99,37,89,0.416,10,32,0.313,15,20,0.750,10,34,44,18,11,7,15,15,-2.0,2025-26
64491,22025,1610612758.0,SAC,Sacramento Kings,0022500181,2025-11-05,SAC vs. GSW,W,239,121,41,83,0.494,11,23,0.478,28,33,0.848,8,39,47,27,7,5,16,18,5.0,2025-26
64492,22025,1610612746.0,LAC,LA Clippers,0022500182,2025-11-06,LAC @ PHX,L,241,102,35,79,0.443,10,31,0.323,22,30,0.733,11,30,41,24,8,4,15,19,-13.0,2025-26
64493,22025,1610612756.0,PHX,Phoenix Suns,0022500182,2025-11-06,PHX vs. LAC,W,239,115,41,92,0.446,19,49,0.388,14,19,0.737,15,29,44,27,13,2,15,23,13.0,2025-26

In [30]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional
0,0020000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986
1,0020000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903
2,0020000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222
3,0020000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722
4,0020000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63949,0052400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708
63950,0052400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057
63951,0052400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126
63952,0052400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611
63953,0052400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820

In [31]:
# Assurer le format datetime pour GAME_DATE
df_games['GAME_DATE'] = pd.to_datetime(df_games['GAME_DATE'])



# Merge avec les infos de match (MATCHUP, SEASON)
match_dataset = match_dataset.merge(
    df_games[['GAME_ID', 'TEAM_ID', 'MATCHUP', 'SEASON','GAME_DATE']],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [32]:

print("match_dataset after merge")
display(match_dataset)

match_dataset after merge

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE
0,0020000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NaN,NaN,NaT
1,0020000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,NaN,NaN,NaT
2,0020000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,NaN,NaN,NaT
3,0020000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NaN,NaN,NaT
4,0020000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63949,0052400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708,NaN,NaN,NaT
63950,0052400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,NaN,NaN,NaT
63951,0052400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,NaN,NaN,NaT
63952,0052400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,NaN,NaN,NaT
63953,0052400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,NaN,NaN,NaT

In [33]:

#display lines with nan values on matchup
print("Lines with NaN in MATCHUP:")
display(match_dataset[match_dataset['MATCHUP'].isna()])

Lines with NaN in MATCHUP:

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE
0,0020000001,1610612752,25,70,3,11,19,24,14,23,37,14,6,4,22,30,72,240.000000,12,15,4,22,5,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,1610612755,38.0,66.0,3.0,8.0,22.0,30.0,8.0,29.0,37.0,27.0,10.0,5.0,13.0,24.0,101.0,240.000000,26.0,9.0,10.0,36.0,4.0,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,NaN,NaN,NaT
1,0020000001,1610612755,38,66,3,8,22,30,8,29,37,27,10,5,13,24,101,240.000000,26,9,10,36,4,113.678208,80.924167,32.729556,0.182441,1.177822,20.832340,0.049657,0.117050,0.092804,12.917368,0.562437,0.596134,0.194474,88.899378,88.899378,50.502014,0.160855,0.601599,0.469504,0.161353,0.382886,0.361238,0.246772,0.319077,0.000000,0.839428,0.116266,0.644489,0.293966,0.049281,0.125861,0.169078,0.233654,0.350402,0.615402,0.247446,0.168090,0.078368,0.629851,0.232997,0.168090,0.508698,0.203276,0.200388,0.194265,0.173397,0.203479,0.208561,0.163576,0.192186,0.195743,0.196602,0.176540,0.217619,0.134035,0.178715,0.194042,0.000000,0.208010,18.242986,1610612752,25.0,70.0,3.0,11.0,19.0,24.0,14.0,23.0,37.0,14.0,6.0,4.0,22.0,30.0,72.0,240.000000,12.0,15.0,4.0,22.0,5.0,80.922299,114.464688,-33.537868,0.163246,0.523610,11.026556,0.056220,0.147483,0.091563,19.763500,0.372955,0.436562,0.193970,88.699676,88.699676,43.962361,0.039403,0.377483,0.365924,0.247518,0.598126,0.458272,0.160368,0.266661,0.000000,0.857836,0.142164,0.650577,0.241035,0.057733,0.039143,0.257106,0.165235,0.409507,0.518244,0.447172,0.197778,0.000000,0.559933,0.405484,0.108844,0.466333,0.213520,0.203724,0.197778,0.193515,0.199331,0.190465,0.232461,0.204200,0.204153,0.200857,0.197202,0.196856,0.199583,0.160243,0.192422,0.000000,0.201207,-14.930903,NaN,NaN,NaT
2,0020000002,1610612739,32,78,2,7,20,32,11,41,52,16,5,8,19,27,86,240.000000,12,12,14,36,8,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,1610612751,31.0,85.0,3.0,10.0,17.0,26.0,12.0,35.0,47.0,24.0,9.0,8.0,12.0,31.0,82.0,240.000000,21.0,13.0,9.0,42.0,8.0,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,NaN,NaN,NaT
3,0020000002,1610612751,31,85,3,10,17,26,12,35,47,24,9,8,12,31,82,240.000000,21,13,9,42,8,83.457417,86.645424,-3.170028,0.186321,1.655972,19.164549,0.044377,0.128634,0.084390,9.645229,0.334428,0.403052,0.190604,98.798017,98.798017,59.042292,0.112319,0.383964,0.309240,0.149999,0.421320,0.418921,0.191348,0.243931,0.000000,0.892640,0.107360,0.589287,0.177226,0.068950,0.074612,0.329879,0.171267,0.412061,0.623859,0.250308,0.227153,0.000000,0.623859,0.250308,0.129859,0.680444,0.195359,0.199699,0.140674,0.162797,0.207021,0.210566,0.241208,0.196126,0.197293,0.200915,0.151191,0.198521,0.187091,0.206165,0.210120,0.000000,0.192918,-2.137222,1610612739,32.0,78.0,2.0,7.0,20.0,32.0,11.0,41.0,52.0,16.0,5.0,8.0,19.0,27.0,86.0,240.000000,12.0,12.0,14.0,36.0,8.0,87.118465,82.284514,4.836236,0.135260,0.953071,12.727431,0.043157,0.154742,0.099091,13.891264,0.403829,0.477510,0.197340,99.597600,99.597600,55.404514,0.027378,0.423046,0.418163,0.189245,0.385467,0.306368,0.150790,0.226623,0.000000,0.905348,0.071110,0.619452,0.225391,0.042091,0.151227,0.250680,0.134511,0.394061,0.380781,0.531441,0.226319,0.000000,0.404284,0.507939,0.179271,0.558568,0.200988,0.201629,0.113160,0.180712,0.189883,0.188048,0.223730,0.215432,0.215471,0.206409,0.202678,0.200235,0.161342,0.223420,0.197098,0.000000,0.194632,4.139722,NaN,NaN,NaT
4,0020000003,1610612753,34,79,6,16,23,33,8,29,37,20,10,9,15,24,97,240.000000,28,9,19,32,1,98.736875,86.636882,12.099993,0.142503,0.857986,12.904542,0.031709,0.133742,0.081268,11.997660,0.475912,0.520254,0.200260,98.899090,98.899090,61.198889,0.118825,0.472056,0.423020,0.148499,0.486995,0.336534,0.267238,0.238280,0.000000,0.799790,0.200210,0.571690,0.237194,0.199434,0.245441,0.229067,0.346846,0.334358,0.459721,0.398473,0.403889,0.000000,0.606531,0.371316,0.186988,0.685047,0.200331,0.201844,0.229832,0.189043,0.227233,0.227924,0.167742,0.196079,0.201831,0.197763,0.182205,0.192654,0.169992,0.065000,0.193451,0.000000,0.204198,7.283056,1610612764,33.0,72.0,4.0,7.0,16.0,24.0,9.0,35.0,44.0,20.0,6.0,1.0,26.0,28.0,86.0,240.000000,15.0,12.0,14.0,42.0,9.0,87.675576,98.295687,-10.619472,0.149045,0.627285,14.817028,0.042904,0.148099,0.098173,19.670639,0.520195,0.553401,0.194765,98.401342,98.401342,53.393403,0.101201,0.485589,0.342879,0.267129,0.470513,0.418830,0.148780,0.185661,0.000000,0.916404,0.083596,0.632414,0.206632,0.148603,0.156626,0.189113,0.165165,0.425926,0.502342,0.467588,0.432986,0.000000,0.600256,0.369674,0.276597,0.604405,0.194938,0.201348,0.157969,0.160486,0.177851,0.170195,0.210115,0.209455,0.210824,0.194940,0.196138,0.138369,0.109583,0.186508,0.215050,0.000000,0.198386,-6.894514,NaN,NaN,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63949,0052400131,1610612758,41,89,13,33,11,15,15,29,44,23,6,4,18,19,106,240.000000,15,13,15,40,8,110.123410,123.832694,-13.692986,0.144001,0.915579,16.246007,0.061248,0.139456,0.094800,13.410542,0.553654,0.568678,0.196805,96.900852,96.900852,64.197361,0.078930,0.533497,0.168455,0.181755,0.589886,0.321300,0.106123,0.242713,1.925417,0.579009,0.412449,0.498701,0.103705,0.374451,0.147024,0.093555,0.120819,0.394996,0.601385,0.356601,0.625625,0.137917,0.614244,0.352284,0.337209,0.444622,0.198443,0.199547,0.199186,0.197010,0.199987,0.198947,0.220836,0.204731,0.202397,0.198671,0.194704,0.193650,0.140420,0.176580,0.204741,0.201187,0.198282,-14.351250,1610612742,41.0,83.0,14.0,28.0,24.0,26.0,10.0,31.0,41.0,29.0,9.0,8.0,9.0,15.0,120.0,240.000000,18.0,4.0,14.0,40.0,4.0,123.867549,110.768076,13.093542,0.179320,1.234705,23.328986,0.043102,0.126057,0.088669,7.650514,0.614891,0.653447,0.190092,96.700401,96.700401,52.394028,0.120096,0.586034,0.319399,0.106316,0.531757,0.167544,0.181331,0.320657,2.229653,0.660342,0.331116,0.484243,0.140879,0.266205,0.119458,0.173500,0.127531,0.343317,0.539994,0.384173,0.710417,0.000000,0.693429,0.230738,0.371341,0.690868,0.189465,0.197248,0.188922,0.192500,0.200256,0.200080,0.177569,0.202057,0.201182,0.211608,0.180998,0.195077,0.211063,0.166207,0.202276,0.192422,0.188871,13.047708,NaN,NaN,NaT
63950,0052400201,1610612737,44,102,16,47,10,12,11,33,44,30,12,3,9,18,114,265.016667,21,14,22,56,8,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,1610612748,48.0,96.0,16.0,42.0,11.0,18.0,13.0,41.0,54.0,33.0,4.0,8.0,14.0,15.0,123.0,265.000000,18.0,17.0,14.0,48.0,3.0,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,NaN,NaN,NaT
63951,0052400201,1610612748,48,96,16,42,11,18,13,41,54,33,4,8,14,15,123,265.000000,18,17,14,48,3,114.115346,109.194151,4.941660,0.175512,1.914025,21.394906,0.052826,0.136744,0.098506,8.743547,0.602740,0.610614,0.188164,96.271151,96.271151,74.389497,0.108900,0.582882,0.188123,0.140615,0.511179,0.117131,0.094058,0.210104,2.789245,0.569122,0.430878,0.531708,0.131616,0.389409,0.104841,0.078883,0.158831,0.400093,0.679972,0.320028,0.594560,0.156132,0.689231,0.310769,0.317894,0.399580,0.200367,0.200068,0.199439,0.200160,0.203244,0.198173,0.193693,0.197318,0.198007,0.203462,0.175619,0.211259,0.195655,0.227722,0.201947,0.191826,0.199943,7.759057,1610612737,44.0,102.0,16.0,47.0,10.0,12.0,11.0,33.0,44.0,30.0,12.0,3.0,9.0,18.0,114.0,265.016667,21.0,14.0,22.0,56.0,8.0,108.972216,113.769398,-4.786328,0.170940,1.701450,19.786856,0.038220,0.132929,0.082033,6.828665,0.533646,0.548288,0.194796,96.542768,96.542768,70.793032,0.094415,0.515043,0.115509,0.094355,0.582867,0.189826,0.139047,0.283225,2.338658,0.528556,0.471444,0.478198,0.000000,0.421953,0.212341,0.069536,0.130952,0.478198,0.664189,0.249212,0.692064,0.218571,0.717321,0.252367,0.401740,0.302049,0.201907,0.198260,0.191661,0.199505,0.163951,0.180012,0.223868,0.200502,0.200689,0.193867,0.160034,0.206388,0.145900,0.193684,0.193772,0.193633,0.199234,-6.091126,NaN,NaN,NaT
63952,0052400211,1610612742,41,87,12,38,12,16,7,29,36,25,9,8,16,17,106,239.983333,14,15,15,44,4,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,1610612763,47.0,100.0,13.0,31.0,13.0,15.0,16.0,34.0,50.0,30.0,8.0,4.0,10.0,17.0,120.0,240.000000,24.0,15.0,19.0,60.0,8.0,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,NaN,NaN,NaT
63953,0052400211,1610612763,47,100,13,31,13,15,16,34,50,30,8,4,10,17,120,240.000000,24,15,19,60,8,118.571125,105.071556,13.509528,0.154672,0.823437,19.079396,0.059757,0.149789,0.100197,4.889924,0.566430,0.582027,0.191697,101.299056,101.299056,62.138194,0.109814,0.532094,0.153846,0.116233,0.542366,0.187143,0.155200,0.164587,2.136944,0.650762,0.334099,0.569661,0.056488,0.328575,0.226652,0.078919,0.205619,0.513310,0.620063,0.349659,0.682240,0.087343,0.648875,0.320847,0.348328,0.327988,0.197052,0.199753,0.185188,0.203577,0.155673,0.161807,0.197832,0.203155,0.201390,0.197460,0.149565,0.187630,0.217161,0.174559,0.196685,0.173665,0.201920,11.408611,1610612742,41.0,87.0,12.0,38.0,12.0,16.0,7.0,29.0,36.0,25.0,9.0,8.0,16.0,17.0,106.0,239.983333,14.0,15.0,15.0,44.0,4.0,103.971838,117.104361,-13.146712,0.159645,1.043291,21.438058,0.028121,0.109295,0.071448,14.196291,0.505059,0.518344,0.194360,102.200355,102.200355,55.776790,0.083048,0.540618,0.184078,0.155320,0.534614,0.150467,0.117294,0.351484,1.775957,0.589597,0.410403,0.375406,0.089519,0.288293,0.120119,0.077834,0.102521,0.286029,0.431148,0.256678,0.465397,0.199927,0.498200,0.243395,0.324056,0.404056,0.199455,0.198674,0.234511,0.197563,0.188766,0.193288,0.179929,0.199788,0.199410,0.199269,0.194797,0.201698,0.189836,0.148746,0.180069,0.178183,0.199691,-8.414820,NaN,NaN,NaT

In [34]:



# Définir si l'équipe joue à domicile
match_dataset['IS_HOME'] = match_dataset['MATCHUP'].str.contains('vs').astype(int)

# Calcul du résultat (win) et écart de points
match_dataset['IS_WIN'] = (match_dataset['points_traditional'] > match_dataset['OPP_points_traditional']).astype(int)
match_dataset['POINT_DIFF'] = match_dataset['points_traditional'] - match_dataset['OPP_points_traditional']

# Conversion GAME_DATE et tri
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])
match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)

ValueError: cannot convert float NaN to integer

In [ ]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE,IS_HOME,IS_WIN,POINT_DIFF
0,0029900001,1610612739,30,77,7,14,17,23,9,29,38,23,10,2,18,27,84,240.000000,16,18,5,18,10,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,1610612752,32.0,74.0,6.0,15.0,22.0,27.0,9.0,35.0,44.0,17.0,10.0,10.0,15.0,23.0,92.0,240.000000,20.0,10.0,8.0,26.0,2.0,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,CLE @ NYK,1999-00,1999-11-02,0,0,-8.0
1,0029900001,1610612752,32,74,6,15,22,27,9,35,44,17,10,10,15,23,92,240.000000,20,10,8,26,2,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,1610612739,30.0,77.0,7.0,14.0,17.0,23.0,9.0,29.0,38.0,23.0,10.0,2.0,18.0,27.0,84.0,240.000000,16.0,18.0,5.0,18.0,10.0,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,NYK vs. CLE,1999-00,1999-11-02,1,1,8.0
2,0029900002,1610612751,36,81,5,12,35,46,15,30,45,11,11,4,18,39,112,240.000000,22,20,8,40,3,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,1610612754,37.0,78.0,6.0,13.0,39.0,53.0,15.0,28.0,43.0,14.0,10.0,3.0,20.0,38.0,119.0,240.016667,19.0,25.0,12.0,42.0,4.0,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,NJN vs. IND,1999-00,1999-11-02,1,0,-7.0
3,0029900002,1610612754,37,78,6,13,39,53,15,28,43,14,10,3,20,38,119,240.016667,19,25,12,42,4,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,1610612751,36.0,81.0,5.0,12.0,35.0,46.0,15.0,30.0,45.0,11.0,11.0,4.0,18.0,39.0,112.0,240.000000,22.0,20.0,8.0,40.0,3.0,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,IND @ NJN,1999-00,1999-11-02,0,1,7.0
4,0029900003,1610612737,31,78,2,6,23,30,16,34,50,15,5,5,23,22,87,240.000000,14,10,14,32,5,89.259479,96.353313,-7.075097,0.127295,0.373726,9.903090,0.064874,0.139126,0.101001,16.693944,0.410884,0.479125,0.200495,98.118501,97.600537,61.293611,0.088329,0.414216,0.401616,0.233748,0.462236,0.185940,0.152675,0.265121,0.503056,0.929368,0.070787,0.714106,0.256272,0.048078,0.153771,0.237661,0.150749,0.457861,0.421989,0.532872,0.000000,0.199514,0.405471,0.594529,0.176944,0.572303,0.202958,0.200886,0.099757,0.222895,0.177422,0.184213,0.191125,0.212502,0.204615,0.215720,0.207392,0.174378,0.154861,0.150347,0.181666,0.028054,0.201412,-2.602917,1610612764,39.0,88.0,3.0,10.0,13.0,16.0,12.0,30.0,42.0,23.0,5.0,5.0,15.0,30.0,94.0,240.000000,21.0,13.0,6.0,40.0,5.0,95.607153,87.699611,7.902674,0.142049,0.605174,20.307479,0.046938,0.118369,0.083026,10.285243,0.505227,0.527368,0.195427,98.120797,98.500015,46.877917,0.105983,0.461744,0.185739,0.153030,0.408839,0.400769,0.234769,0.346544,0.702847,0.878051,0.090977,0.792576,0.317607,0.079125,0.079987,0.097327,0.239451,0.474969,0.487619,0.481409,0.131875,0.000000,0.564075,0.404953,0.054433,0.349670,0.204716,0.200208,0.085926,0.136903,0.190875,0.203007,0.185406,0.196825,0.197388,0.189788,0.200875,0.185517,0.172653,0.155711,0.199349,0.080037,0.204833,4.042986,ATL @ WAS,1999-00,1999-11-02,0,0,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76342,0042400401,1610612760,39,98,11,30,21,24,10,29,39,13,14,6,6,19,110,240.016667,11,11,11,46,7,104.859211,107.238254,-2.401319,0.089877,0.484480,9.231408,0.032102,0.126582,0.073159,4.215554,0.471415,0.518615,0.190986,104.398813,104.097747,65.037497,0.097399,0.455725,0.253861,0.066125,0.585600,0.256203,0.242994,0.305840,2.829040,0.638792,0.358499,0.523928,0.053338,0.277455,0.101775,0.178516,0.108151,0.470590,0.280170,0.548314,0.341042,0.292109,0.451021,0.528911,0.280632,0.579554,0.197089,0.199259,0.183445,0.203555,0.203944,0.205643,0.158191,0.195664,0.189841,0.191115,0.166873,0.207506,0.252223,0.156445,0.205720,0.204903,0.201040,-1.280814,1610612754,39.0,82.0,18.0,39.0,15.0,21.0,13.0,43.0,56.0,24.0,1.0,7.0,24.0,22.0,111.0,240.016667,4.0,12.0,10.0,34.0,6.0,107.199743,106.020887,1.185473,0.152824,1.487171,16.042157,0.054027,0.135550,0.102712,16.549691,0.590604,0.622814,0.194014,104.398840,103.499456,61.453580,0.105077,0.587677,0.257399,0.241239,0.456693,0.248252,0.066348,0.198115,2.300604,0.501280,0.498720,0.367759,0.077094,0.487458,0.102077,0.145064,0.030612,0.290827,0.311811,0.520492,0.785258,0.148566,0.577500,0.422500,0.453506,0.406064,0.201986,0.200134,0.195214,0.196461,0.208137,0.204329,0.181644,0.190189,0.193941,0.198113,0.190323,0.068954,0.205017,0.172056,0.188080,0.209822,0.200037,3.767655,OKC vs. IND,2024-25,2025-06-05,1,0,-1.0
76343,0042400402,1610612754,37,82,14,40,19,26,7,28,35,27,9,6,15,25,107,240.000000,17,10,9,34,4,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,1610612760,40.0,82.0,14.0,36.0,29.0,33.0,11.0,32.0,43.0,25.0,10.0,4.0,13.0,20.0,123.0,240.000000,14.0,9.0,4.0,42.0,6.0,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,IND @ OKC,2024-25,2025-06-08,0,0,-16.0
76344,0042400402,1610612760,40,82,14,36,29,33,11,32,43,25,10,4,13,20,123,240.000000,14,9,4,42,6,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,1610612754,37.0,82.0,14.0,40.0,19.0,26.0,7.0,28.0,35.0,27.0,9.0,6.0,15.0,25.0,107.0,240.000000,17.0,10.0,9.0,34.0,4.0,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,OKC vs. IND,2024-25,2025-06-08,1,1,16.0
76345,0042400403,1610612754,44,85,9,27,19,22,7,29,36,24,13,11,13,24,116,240.000000,21,13,17,50,4,114.081778,103.844535,10.243340,0.143614,0.890670,13.519639,0.032210,0.127237,0.081195,10.168583,0.564719,0.589556,0.194711,101.940403,102.401259,58.636806,0.110640,0.569751,0.258165,0.138367,0.532022,0.386116,0.185964,0.233093,2.106042,0.654474,0.332749,0.624951,0.215150,0.236199,0.131332,0.125948,0.219943,0.409799,0.499780,0.487443,0.562083,0.037847,0.581615,0.405607,0.284580,0.449041,0.196540,0.199064,0.195040,0.196882,0.174378,0.182395,0.240243,0.199543,0.201736,0.198057,0.192505,0.186220,0.177785,0.171336,0.193431,0.188285,0.193799,4.867153,1610612760,37.0,79.0,10.0,22.0,23.0,30.0,9.0,33.0,42.0,16.0,6.0,4.0,17.0,20.0,107.0,240.000000,14.0,7.0,10.0,48.0,11.0,104.041729,113.766938,-9.725208,0.109897,1.188749,12.576111,0.040029,0.148027,0.094363,13.171382,0.551383,0.595842,0.188548,101.939283,102.497244,68.000069,0.090457,0.532462,0.380398,0.185438,0.571176,0.265022,0.137716,0.176117,3.636528,0.704326,0.294285,0.459764,0.040943,0.306684,0.105949,0.183192,0.130573,0.418821,0.245000,0.403889,0.292118,0.335799,0.534992,0.414800,0.405356,0.556018,0.200116,0.200735,0.173265,0.175914,0.185293,0.185213,0.194253,0.195259,0.195451,0.197819,0.177444,0.229913,0.182049,0.190598,0.195926,0.185801,0.197910,-5.147639,IND vs. OKC,2024-25,2025-06-11,1,1,9.0
76346,0042400403,1610612760,37,79,10,22,23,30,9,33,42,16,6,4,17,20,107,240.000000,14,7,10,48,11,104.041729,113.766938,-9.725208,0.109897,1.188749,12.576111,0.040029,0.148027,0.094363,13.171382,0.551383,0.595842,0.188548,101.939283,102.497244,68.000069,0.090457,0.532462,0.380398,0.185438,0.571176,0.265022,0.137716,0.176117,3.636528,0.704326,0.294285,0.459764,0.040943,0.306684,0.105949,0.183192,0.130573,0.418821,0.245000,0.403889,0.292118,0.335799,0.534992,0.414800,0.405356,0.556018,0.200116,0.200735,0.173265,0.175914,0.185293,0.185213,0.194253,0.195259,0.195451,0.197819,0.177444,0.229913,0.182049,0.190598,0.195926,0.185801,0.197910,-5.147639,1610612754,44.0,85.0,9.0,27.0,19.0,22.0,7.0,29.0,36.0,24.0,13.0,11.0,13.0,24.0,116.0,240.000000,21.0,13.0,17.0,50.0,4.0,114.081778,103.844535,10.243340,0.143614,0.890670,13.519639,0.032210,0.127237,0.081195,10.168583,0.564719,0.589556,0.194711,101.940403,102.401259,58.636806,0.110640,0.569751,0.258165,0.138367,0.532022,0.386116,0.185964,0.233093,2.106042,0.654474,0.332749,0.624951,0.215150,0.236199,0.131332,0.125948,0.219943,0.409799,0.499780,0.487443,0.562083,0.037847,0.581615,0.405607,0.284580,0.449041,0.196540,0.199064,0.195040,0.196882,0.174378,0.182395,0.240243,0.199543,0.201736,0.198057,0.192505,0.186220,0.177785,0.171336,0.193431,0.188285,0.193799,4.867153,OKC @ IND,2024-25,2025-06-11,0,0,-9.0

# SPECIAL FOR ODDS : Keep only season past 2010-11

In [ ]:
# # get first line with season 2010-11 and cut all lines before
# first_season = match_dataset[match_dataset['SEASON'] == '2010-11'].index[0]
# match_dataset = match_dataset.iloc[first_season:].reset_index(drop=True)
# match_dataset

# Merge Odds with dataset

In [ ]:
all_odds_df = merge_odds_csv_files(DATA_ODDS_HISTORY_DIR)

match_dataset = match_odds_with_dataset_test(all_odds_df, match_dataset)

------------------ Nombre de lignes sans cotes (home/away): 28120 ------------------

In [ ]:
match_dataset

,GAME_ID,TEAM_ID,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,points_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_TEAM_ID,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,GAME_DATE,IS_HOME,IS_WIN,POINT_DIFF,TEAM_NAME,OPPONENT_NAME,ODDS,OPP_ODDS
0,0029900001,1610612739,30,77,7,14,17,23,9,29,38,23,10,2,18,27,84,240.000000,16,18,5,18,10,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,1610612752,32.0,74.0,6.0,15.0,22.0,27.0,9.0,35.0,44.0,17.0,10.0,10.0,15.0,23.0,92.0,240.000000,20.0,10.0,8.0,26.0,2.0,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,CLE @ NYK,1999-00,1999-11-02,0,0,-8.0,cleveland cavaliers,new york knicks,NaN,NaN
1,0029900001,1610612752,32,74,6,15,22,27,9,35,44,17,10,10,15,23,92,240.000000,20,10,8,26,2,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,1610612739,30.0,77.0,7.0,14.0,17.0,23.0,9.0,29.0,38.0,23.0,10.0,2.0,18.0,27.0,84.0,240.000000,16.0,18.0,5.0,18.0,10.0,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,NYK vs. CLE,1999-00,1999-11-02,1,1,8.0,new york knicks,cleveland cavaliers,NaN,NaN
2,0029900002,1610612751,36,81,5,12,35,46,15,30,45,11,11,4,18,39,112,240.000000,22,20,8,40,3,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,1610612754,37.0,78.0,6.0,13.0,39.0,53.0,15.0,28.0,43.0,14.0,10.0,3.0,20.0,38.0,119.0,240.016667,19.0,25.0,12.0,42.0,4.0,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,NJN vs. IND,1999-00,1999-11-02,1,0,-7.0,brooklyn nets,indiana pacers,NaN,NaN
3,0029900002,1610612754,37,78,6,13,39,53,15,28,43,14,10,3,20,38,119,240.016667,19,25,12,42,4,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,1610612751,36.0,81.0,5.0,12.0,35.0,46.0,15.0,30.0,45.0,11.0,11.0,4.0,18.0,39.0,112.0,240.000000,22.0,20.0,8.0,40.0,3.0,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,IND @ NJN,1999-00,1999-11-02,0,1,7.0,indiana pacers,brooklyn nets,NaN,NaN
4,0029900003,1610612737,31,78,2,6,23,30,16,34,50,15,5,5,23,22,87,240.000000,14,10,14,32,5,89.259479,96.353313,-7.075097,0.127295,0.373726,9.903090,0.064874,0.139126,0.101001,16.693944,0.410884,0.479125,0.200495,98.118501,97.600537,61.293611,0.088329,0.414216,0.401616,0.233748,0.462236,0.185940,0.152675,0.265121,0.503056,0.929368,0.070787,0.714106,0.256272,0.048078,0.153771,0.237661,0.150749,0.457861,0.421989,0.532872,0.000000,0.199514,0.405471,0.594529,0.176944,0.572303,0.202958,0.200886,0.099757,0.222895,0.177422,0.184213,0.191125,0.212502,0.204615,0.215720,0.207392,0.174378,0.154861,0.150347,0.181666,0.028054,0.201412,-2.602917,1610612764,39.0,88.0,3.0,10.0,13.0,16.0,12.0,30.0,42.0,23.0,5.0,5.0,15.0,30.0,94.0,240.000000,21.0,13.0,6.0,40.0,5.0,95.607153,87.699611,7.902674,0.142049,0.605174,20.307479,0.046938,0.118369,0.083026,10.285243,0.505227,0.527368,0.195427,98.120797,98.500015,46.877917,0.105983,0.461744,0.185739,0.153030,0.408839,0.400769,0.234769,0.346544,0.702847,0.878051,0.090977,0.792576,0.317607,0.079125,0.079987,0.097327,0.239451,0.474969,0.487619,0.481409,0.131875,0.000000,0.564075,0.404953,0.054433,0.349670,0.204716,0.200208,0.085926,0.136903,0.190875,0.203007,0.185406,0.196825,0.197388,0.189788,0.200875,0.185517,0.172653,0.155711,0.199349,0.080037,0.204833,4.042986,ATL @ WAS,1999-00,1999-11-02,0,0,-7.0,atlanta hawks,washington wizards,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66196,0042400401,1610612760,39,98,11,30,21,24,10,29,39,13,14,6,6,19,110,240.016667,11,11,11,46,7,104.859211,107.238254,-2.401319,0.089877,0.484480,9.231408,0.032102,0.126582,0.073159,4.215554,0.471415,0.518615,0.190986,104.398813,104.097747,65.037497,0.097399,0.455725,0.253861,0.066125,0.585600,0.256203,0.242994,0.305840,2.829040,0.638792,0.358499,0.523928,0.053338,0.277455,0.101775,0.178516,0.108151,0.470590,0.280170,0.548314,0.341042,0.292109,0.451021,0.528911,0.280632,0.579554,0.197089,0.199259,0.183445,0.203555,0.203944,0.205643,0.158191,0.195664,0.189841,0.191115,0.166873,0.207506,0.252223,0.156445,0.205720,0.204903,0.201040,-1.280814,1610612754,39.0,82.0,18.0,39.0,15.0,21.0,13.0,43.0,56.0,24.0,1.0,7.0,24.0,22.0,111.0,240.016667,4.0,12.0,10.0,34.0,6.0,107.199743,106.020887,1.185473,0.152824,1.487171,16.042157,0.054027,0.135550,0.102712,16.549691,0.590604,0.622814,0.194014,104.398840,103.499456,61.453580,0.105077,0.587677,0.257399,0.241239,0.456693,0.248252,0.066348,0.198115,2.300604,0.501280,0.498720,0.367759,0.077094,0.487458,0.102077,0.145064,0.030612,0.290827,0.311811,0.520492,0.785258,0.148566,0.577500,0.422500,0.453506,0.406064,0.201986,0.200134,0.195214,0.196461,0.208137,0.204329,0.181644,0.190189,0.193941,0.198113,0.190323,0.068954,0.205017,0.172056,0.188080,0.209822,0.200037,3.767655,OKC vs. IND,2024-25,2025-06-05,1,0,-1.0,oklahoma city thunder,indiana pacers,NaN,NaN
66197,0042400402,1610612754,37,82,14,40,19,26,7,28,35,27,9,6,15,25,107,240.000000,17,10,9,34,4,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,1610612760,40.0,82.0,14.0,36.0,29.0,33.0,11.0,32.0,43.0,25.0,10.0,4.0,13.0,20.0,123.0,240.000000,14.0,9.0,4.0,42.0,6.0,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,IND @ OKC,2024-25,2025-06-08,0,0,-16.0,indiana pacers,oklahoma city thunder,NaN,NaN
66198,0042400402,1610612760,40,82,14,36,29,33,11,32,43,25,10,4,13,20,123,240.000000,14,9,4,42,6,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,1610612754,37.0,82.0,14.0,40.0,19.0,26.0,7.0,28.0,35.0,27.0,9.0,6.0,15.0,25.0,107.0,240.000000,17.0,10.0,9.0,34.0,4.0,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,OKC vs. IND,2024-25,2025-06-08,1,1,16.0,oklahoma city thunder,indiana pacers,NaN,NaN
66199,0042400403,1610612754,44,85,9,27,19,22,7,29,36,24,13,11,13,24,116,240.000000,21,13,17,50,4,114.081778,103.844535,10.243340,0.143614,0.890670,13.519639,0.032210,0.127237,0.081195,10.168583,0.564719,0.589556,0.194711,101.940403,102.401259,58.636806,0.110640,0.569751,0.258165,0.138367,0.532022,0.386116,0.185964,0.233093,2.106042,0.654474,0.332749,0.624951,0.215150,0.236199,0.131332,0.125948,0.219943,0.409799,0.499780,0.487443,0.562083,0.037847,0.581615,0.405607,0.284580,0.449041,0.196540,0.199064,0.195040,0.196882,0.174378,0.182395,0.240243,0.199543,0.201736,0.198057,0.192505,0.186220,0.177785,0.171336,0.193431,0.188285,0.193799,4.867153,1610612760,37.0,79.0,10.0,22.0,23.0,30.0,9.0,33.0,42.0,16.0,6.0,4.0,17.0,20.0,107.0,240.000000,14.0,7.0,10.0,48.0,11.0,104.041729,113.766938,-9.725208,0.109897,1.188749,12.576111,0.040029,0.148027,0.094363,13.171382,0.551383,0.595842,0.188548,101.939283,102.497244,68.000069,0.090457,0.532462,0.380398,0.185438,0.571176,0.265022,0.137716,0.176117,3.636528,0.704326,0.294285,0.459764,0.040943,0.306684,0.105949,0.183192,0.130573,0.418821,0.245000,0.403889,0.292118,0.335799,0.534992,0.414800,0.405356,0.556018,0.200116,0.200735,0.173265,0.175914,0.185293,0.185213,0.194253,0.195259,0.195451,0.197819,0.177444,0.229913,0.182049,0.190598,0.195926,0.185801,0.197910,-5.147639,IND vs. OKC,2024-25,2025-06-11,1,1,9.0,indiana pacers,oklahoma city thunder,NaN,NaN
66200,0042400403,1610612760,37,79,10,22,23,30,9,33,42,16,6,4,17,20,107,240.000000,14,7,10,48,11,104.041729,113.766938,-9.725208,0.109897,1.188749,12.576111,0.040029,0.148027,0.094363,13.171382,0.551383,0.595842,0.188548,101.939283,102.497244,68.000069,0.090457,0.532462,0.380398,0.185438,0.571176,0.265022,0.137716,0.176117,3.636528,0.704326,0.294285,0.459764,0.040943,0.306684,0.105949,0.183192,0.130573,0.418821,0.245000,0.403889,0.292118,0.335799,0.534992,0.414800,0.405356,0.556018,0.200116,0.200735,0.173265,0.175914,0.185293,0.185213,0.194253,0.195259,0.195451,0.197819,0.177444,0.229913,0.182049,0.190598,0.195926,0.185801,0.197910,-5.147639,1610612754,44.0,85.0,9.0,27.0,19.0,22.0,7.0,29.0,36.0,24.0,13.0,11.0,13.0,24.0,116.0,240.000000,21.0,13.0,17.0,50.0,4.0,114.081778,103.844535,10.243340,0.143614,0.890670,13.519639,0.032210,0.127237,0.081195,10.168583,0.564719,0.589556,0.194711,101.940403,102.401259,58.636806,0.110640,0.569751,0.258165,0.138367,0.532022,0.386116,0.185964,0.233093,2.106042,0.654474,0.332749,0.624951,0.215150,0.236199,0.131332,0.125948,0.219943,0.409799,0.499780,0.487443,0.562083,0.037847,0.581615,0.405607,0.284580,0.449041,0.196540,0.199064,0.195040,0.196882,0.174378,0.182395,0.240243,0.199543,0.201736,0.198057,0.192505,0.186220,0.177785,0.171336,0.193431,0.188285,0.193799,4.867153,OKC @ IND,2024-25,2025-06-11,0,0,-9.0,oklahoma city thunder,indiana pacers,NaN,NaN

# Merge match_dataset with df_team_features_final on TEAM and GAME

In [ ]:

#team id as str
match_dataset['TEAM_ID'] = match_dataset['TEAM_ID'].astype(str)
match_dataset['GAME_ID'] = match_dataset['GAME_ID'].astype(str)

#date as datetime
match_dataset['GAME_DATE'] = pd.to_datetime(match_dataset['GAME_DATE'])

df_team_features_final['TEAM_ID'] = df_team_features_final['TEAM_ID'].astype(str)
df_team_features_final['GAME_ID'] = df_team_features_final['GAME_ID'].astype(str)
df_team_features_final['GAME_DATE'] = pd.to_datetime(df_team_features_final['GAME_DATE'])



# Merge match_dataset with df_team_features_final on TEAM and GAME, keep GAME_DATE
match_dataset = match_dataset.merge(
    df_team_features_final[['GAME_ID', 'TEAM_ID', 'GAME_DATE'] + df_team_features_final.columns.difference(['GAME_ID', 'TEAM_ID', 'GAME_DATE']).tolist()],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)



# match_dataset_ = match_dataset.merge(
#     df_team_features_final,
#     on=['GAME_ID', 'TEAM_ID'],
#     how='left'
# )
#remove duplicates
match_dataset = match_dataset.drop_duplicates(subset=['GAME_ID', 'TEAM_ID'])

In [ ]:
#sort by GAME_DATE and GAME_ID
#match_dataset = match_dataset.sort_values(['GAME_DATE', 'GAME_ID']).reset_index(drop=True)



#print GAME_DATE_x and GAME_DATE_y to check if they are the same
print("GAME_DATE_x and GAME_DATE_y are the same:", (match_dataset['GAME_DATE_x'] == match_dataset['GAME_DATE_y']).all())

#drop GAME_DATE_x and GAME_DATE_y to GAME_DATE
match_dataset['GAME_DATE'] = match_dataset['GAME_DATE_x']
match_dataset = match_dataset.drop(columns=['GAME_DATE_x', 'GAME_DATE_y'])



#display cols in common match_dataset and df_team_features_final
common_cols = set(match_dataset.columns).intersection(set(df_team_features_final.columns))
print("Common columns between match_dataset and df_team_features_final:")
display(common_cols)

GAME_DATE_x and GAME_DATE_y are the same: True
Common columns between match_dataset and df_team_features_final:

{'GAME_DATE',
 'GAME_ID',
 'TEAM_ID',
 'has_absent',
 'has_top_absent',
 'num_absent',
 'num_absent_other',
 'num_injured',
 'num_personal',
 'num_present',
 'num_resting',
 'num_suspended',
 'player_perf_score_mean',
 'player_perf_score_sum',
 'top_player_absent',
 'top_player_absent_other',
 'top_player_absent_other_rate',
 'top_player_absent_rate',
 'top_player_count',
 'top_player_injured',
 'top_player_injury_rate',
 'top_player_personal',
 'top_player_personal_rate',
 'top_player_resting',
 'top_player_resting_rate',
 'top_player_suspended',
 'top_player_suspension_rate'}

# Reorder columns for visualisation

In [ ]:
cols_first = ['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN','POINT_DIFF','has_absent','has_top_absent','num_absent','top_player_absent', 'points_traditional','ODDS','OPP_ODDS']
other_cols = [col for col in match_dataset.columns if col not in cols_first]
match_dataset = match_dataset[cols_first + other_cols]
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,has_absent,has_top_absent,num_absent,top_player_absent,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME,num_absent_other,num_injured,num_personal,num_present,num_resting,num_suspended,player_perf_score_mean,player_perf_score_sum,top_player_absent_other,top_player_absent_other_rate,top_player_absent_rate,top_player_count,top_player_injured,top_player_injury_rate,top_player_personal,top_player_personal_rate,top_player_resting,top_player_resting_rate,top_player_suspended,top_player_suspension_rate
0,0029900001,1999-11-02,1610612739,1610612752,0,0,-8.0,1,0,1,0,84,NaN,NaN,30,77,7,14,17,23,9,29,38,23,10,2,18,27,240.000000,16,18,5,18,10,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,32.0,74.0,6.0,15.0,22.0,27.0,9.0,35.0,44.0,17.0,10.0,10.0,15.0,23.0,92.0,240.000000,20.0,10.0,8.0,26.0,2.0,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,CLE @ NYK,1999-00,cleveland cavaliers,new york knicks,1,0,0,11,0,0,13.175000,158.1,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
1,0029900001,1999-11-02,1610612752,1610612739,1,1,8.0,1,0,3,0,92,NaN,NaN,32,74,6,15,22,27,9,35,44,17,10,10,15,23,240.000000,20,10,8,26,2,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,30.0,77.0,7.0,14.0,17.0,23.0,9.0,29.0,38.0,23.0,10.0,2.0,18.0,27.0,84.0,240.000000,16.0,18.0,5.0,18.0,10.0,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,NYK vs. CLE,1999-00,new york knicks,cleveland cavaliers,3,0,0,9,0,0,14.608333,175.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
2,0029900002,1999-11-02,1610612751,1610612754,1,0,-7.0,1,1,2,1,112,NaN,NaN,36,81,5,12,35,46,15,30,45,11,11,4,18,39,240.000000,22,20,8,40,3,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,37.0,78.0,6.0,13.0,39.0,53.0,15.0,28.0,43.0,14.0,10.0,3.0,20.0,38.0,119.0,240.016667,19.0,25.0,12.0,42.0,4.0,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,NJN vs. IND,1999-00,brooklyn nets,indiana pacers,2,0,0,10,0,0,14.958333,179.5,1,0.2,0.2,5,0,0.0,0,0.0,0,0.0,0,0.0
3,0029900002,1999-11-02,1610612754,1610612751,0,1,7.0,1,0,2,0,119,NaN,NaN,37,78,6,13,39,53,15,28,43,14,10,3,20,38,240.016667,19,25,12,42,4,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,36.0,81.0,5.0,12.0,35.0,46.0,15.0,30.0,45.0,11.0,11.0,4.0,18.0,39.0,112.0,240.000000,22.0,20.0,8.0,40.0,3.0,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,IND @ NJN,1999-00,indiana pacers,brooklyn nets,2,0,0,10,0,0,15.383333,184.6,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
4,0029900003,1999-11-02,1610612737,1610612764,0,0,-7.0,1,1,2,1,87,NaN,NaN,31,78,2,6,23,30,16,34,50,15,5,5,23,22,240.000000,14,10,14,32,5,89.259479,96.353313,-7.075097,0.127295,0.373726,9.903090,0.064874,0.139126,0.101001,16.693944,0.410884,0.479125,0.200495,98.118501,97.600537,61.293611,0.088329,0.414216,0.401616,0.233748,0.462236,0.185940,0.152675,0.265121,0.503056,0.929368,0.070787,0.714106,0.256272,0.048078,0.153771,0.237661,0.150749,0.457861,0.421989,0.532872,0.000000,0.199514,0.405471,0.594529,0.176944,0.572303,0.202958,0.200886,0.099757,0.222895,0.177422,0.184213,0.191125,0.212502,0.204615,0.215720,0.207392,0.174378,0.154861,0.150347,0.181666,0.028054,0.201412,-2.602917,39.0,88.0,3.0,10.0,13.0,16.0,12.0,30.0,42.0,23.0,5.0,5.0,15.0,30.0,94.0,240.000000,21.0,13.0,6.0,40.0,5.0,95.607153,87.699611,7.902674,0.142049,0.605174,20.307479,0.046938,0.118369,0.083026,10.285243,0.505227,0.527368,0.195427,98.120797,98.500015,46.877917,0.105983,0.461744,0.185739,0.153030,0.408839,0.400769,0.234769,0.346544,0.702847,0.878051,0.090977,0.792576,0.317607,0.079125,0.079987,0.097327,0.239451,0.474969,0.487619,0.481409,0.131875,0.000000,0.564075,0.404953,0.054433,0.349670,0.204716,0.200208,0.085926,0.136903,0.190875,0.203007,0.185406,0.196825,0.197388,0.189788,0.200875,0.185517,0.172653,0.155711,0.199349,0.080037,0.204833,4.042986,ATL @ WAS,1999-00,atlanta hawks,washington wizards,1,0,1,10,0,0,13.041667,156.5,0,0.0,0.2,5,0,0.0,1,0.2,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66196,0042400401,2025-06-05,1610612760,1610612754,1,0,-1.0,1,0,3,0,110,NaN,NaN,39,98,11,30,21,24,10,29,39,13,14,6,6,19,240.016667,11,11,11,46,7,104.859211,107.238254,-2.401319,0.089877,0.484480,9.231408,0.032102,0.126582,0.073159,4.215554,0.471415,0.518615,0.190986,104.398813,104.097747,65.037497,0.097399,0.455725,0.253861,0.066125,0.585600,0.256203,0.242994,0.305840,2.829040,0.638792,0.358499,0.523928,0.053338,0.277455,0.101775,0.178516,0.108151,0.470590,0.280170,0.548314,0.341042,0.292109,0.451021,0.528911,0.280632,0.579554,0.197089,0.199259,0.183445,0.203555,0.203944,0.205643,0.158191,0.195664,0.189841,0.191115,0.166873,0.207506,0.252223,0.156445,0.205720,0.204903,0.201040,-1.280814,39.0,82.0,18.0,39.0,15.0,21.0,13.0,43.0,56.0,24.0,1.0,7.0,24.0,22.0,111.0,240.016667,4.0,12.0,10.0,34.0,6.0,107.199743,106.020887,1.185473,0.152824,1.487171,16.042157,0.054027,0.135550,0.102712,16.549691,0.590604,0.622814,0.194014,104.398840,103.499456,61.453580,0.105077,0.587677,0.257399,0.241239,0.456693,0.248252,0.066348,0.198115,2.300604,0.501280,0.498720,0.367759,0.077094,0.487458,0.102077,0.145064,0.030612,0.290827,0.311811,0.520492,0.785258,0.148566,0.577500,0.422500,0.453506,0.406064,0.201986,0.200134,0.195214,0.196461,0.208137,0.204329,0.181644,0.190189,0.193941,0.198113,0.190323,0.068954,0.205017,0.172056,0.188080,0.209822,0.200037,3.767655,OKC vs. IND,2024-25,oklahoma city thunder,indiana pacers,3,0,0,11,0,0,13.592857,190.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
66197,0042400402,2025-06-08,1610612754,1610612760,0,0,-16.0,1,0,3,0,107,NaN,NaN,37,82,14,40,19,26,7,28,35,27,9,6,15,25,240.000000,17,10,9,34,4,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,40.0,82.0,14.0,36.0,29.0,33.0,11.0,32.0,43.0,25.0,10.0,4.0,13.0,20.0,123.0,240.000000,14.0,9.0,4.0,42.0,6.0,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,IND @ OKC,2024-25,indiana pacers,oklahoma city thunder,1,2,0,12,0,0,12.633333,189.5,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
66198,0042400402,2025-06-08,1610612760,1610612754,1,1,16.0,0,0,0,0,123,NaN,NaN,40,82,14,36,29,33,11,32,43,25,10,4,13,20,240.000000,14,9,4,42,6,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,37.0,82.0,14.0,40.0,19.0,26.0,7.0,28.0,35.0,27.0,9.0,6.0,15.0,25.0,107.0,240.000000,17.0,10.0,9.0,34.0,4.0,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,OKC vs. IND,2024-25,oklahoma city thunder,indiana pacers,0,0,0,14,0,0,15.221429,213.1,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0
66199,0042400403,2025-06-11,1610612754,1610612760,1,1,9.0,1,0,5,0,116,NaN,NaN,44,85,9,27,19,22,7,29,36,24,13,11,13,24,240.000000,21,13,17,50,4,114.081778,103.844535,10.243340,0.143614,0.890670,13.519639,0.032210,0.127237,0.081195,10.168583,0.564719,0.589556,0.194711,101.940403,102.401259,58.636806,0.110640,0.569751,0.258165,0.138367,0.532022,0.386116,0.185964,0.233093,2.106042,0.654474,0.332749,0.624951,0.215150,0.236199,0.131332,0.125948,0.219943,0.409799,0.499780,0.487443,0.562083,0.037847,0.581615,0.405607,0.284580,0.449041,0.196540,0.199064,0.195040,0.196882,0.174378,0.182395,0.240243,0.199543,0.201736,0.198057,0.192505,0.186220,0.177785,0.171336,0.193431,0.188285,0.193799,4.867153,37.0,79.0,10.0,22.0,23.0,30.0,9.0,33.0,42.0,16.0,6.0,4.0,17.0,20.0,107.0,240.000000,14.0,7.0,10.0,48.0,11.0,104.041729,113.766938,-9.725208,0.109897,1.188749,12.576111,0.040029,0.148027,0.094363,13.171382,0.551383,0.595842,0.188548,101.939283,102.497244,68.000069,0.090457,0.532462,0.380398,0.185438,0.571176,0.265022,0.137716,0.176117,3.636528,0.704326,0.294285,0.459764,0.040943,0.306684,0.105949,0.183192,0.130573,0.418821,0.245000,0.403889,0.292118,0.335799,0.534992,0.414800,0.405356,0.556018,0.200116,0.200735,0.173265,0.175914,0.185293,0.185213,0.194253,0.195259,0.195451,0.197819,0.177444,0.229913,0.182049,0.190598,0.195926,0.185801,0.197910,-5.147639,IND vs. OKC,2024-25,indiana pacers,oklahoma city thunder,3,2,0,10,0,0,13.746667,206.2,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0

# Add OPP cols for player stats

In [ ]:
opp_cols = [f"OPP_{col}" for col in cols_player_stats]
df_opp = match_dataset.rename(columns={col: f"OPP_{col}" for col in cols_player_stats})

match_dataset = pd.merge(
    match_dataset,
    df_opp[['GAME_ID', 'TEAM_ID'] + opp_cols],
    on=['GAME_ID', 'TEAM_ID'],
    how='left'
)

In [ ]:
match_dataset

,GAME_ID,GAME_DATE,TEAM_ID,OPP_TEAM_ID,IS_HOME,IS_WIN,POINT_DIFF,has_absent,has_top_absent,num_absent,top_player_absent,points_traditional,ODDS,OPP_ODDS,fieldGoalsMade_traditional,fieldGoalsAttempted_traditional,threePointersMade_traditional,threePointersAttempted_traditional,freeThrowsMade_traditional,freeThrowsAttempted_traditional,reboundsOffensive_traditional,reboundsDefensive_traditional,reboundsTotal_traditional,assists_traditional,steals_traditional,blocks_traditional,turnovers_traditional,foulsPersonal_traditional,MINUTES_PLAYED,pointsOffTurnovers_misc,pointsSecondChance_misc,pointsFastBreak_misc,pointsPaint_misc,blocksAgainst_misc,offensiveRating_advanced,defensiveRating_advanced,netRating_advanced,assistPercentage_advanced,assistToTurnover_advanced,assistRatio_advanced,offensiveReboundPercentage_advanced,defensiveReboundPercentage_advanced,reboundPercentage_advanced,turnoverRatio_advanced,effectiveFieldGoalPercentage_advanced,trueShootingPercentage_advanced,usagePercentage_advanced,estimatedPace_advanced,pace_advanced,possessions_advanced,PIE_advanced,effectiveFieldGoalPercentage_fourfactors,freeThrowAttemptRate_fourfactors,teamTurnoverPercentage_fourfactors,oppEffectiveFieldGoalPercentage_fourfactors,oppFreeThrowAttemptRate_fourfactors,oppTeamTurnoverPercentage_fourfactors,oppOffensiveReboundPercentage_fourfactors,foulsDrawn_misc,percentageFieldGoalsAttempted2pt_scoring,percentageFieldGoalsAttempted3pt_scoring,percentagePoints2pt_scoring,percentagePointsMidrange2pt_scoring,percentagePoints3pt_scoring,percentagePointsFastBreak_scoring,percentagePointsFreeThrow_scoring,percentagePointsOffTurnovers_scoring,percentagePointsPaint_scoring,percentageAssisted2pt_scoring,percentageUnassisted2pt_scoring,percentageAssisted3pt_scoring,percentageUnassisted3pt_scoring,percentageAssistedFGM_scoring,percentageUnassistedFGM_scoring,threePointersPercentage_traditional,freeThrowsPercentage_traditional,percentageFieldGoalsMade_usage,percentageFieldGoalsAttempted_usage,percentageThreePointersMade_usage,percentageThreePointersAttempted_usage,percentageFreeThrowsMade_usage,percentageFreeThrowsAttempted_usage,percentageReboundsOffensive_usage,percentageReboundsDefensive_usage,percentageReboundsTotal_usage,percentageAssists_usage,percentageTurnovers_usage,percentageSteals_usage,percentageBlocks_usage,percentageBlocksAllowed_usage,percentagePersonalFouls_usage,percentagePersonalFoulsDrawn_usage,percentagePoints_usage,plusMinusPoints_traditional,OPP_fieldGoalsMade_traditional,OPP_fieldGoalsAttempted_traditional,OPP_threePointersMade_traditional,OPP_threePointersAttempted_traditional,OPP_freeThrowsMade_traditional,OPP_freeThrowsAttempted_traditional,OPP_reboundsOffensive_traditional,OPP_reboundsDefensive_traditional,OPP_reboundsTotal_traditional,OPP_assists_traditional,OPP_steals_traditional,OPP_blocks_traditional,OPP_turnovers_traditional,OPP_foulsPersonal_traditional,OPP_points_traditional,OPP_MINUTES_PLAYED,OPP_pointsOffTurnovers_misc,OPP_pointsSecondChance_misc,OPP_pointsFastBreak_misc,OPP_pointsPaint_misc,OPP_blocksAgainst_misc,OPP_offensiveRating_advanced,OPP_defensiveRating_advanced,OPP_netRating_advanced,OPP_assistPercentage_advanced,OPP_assistToTurnover_advanced,OPP_assistRatio_advanced,OPP_offensiveReboundPercentage_advanced,OPP_defensiveReboundPercentage_advanced,OPP_reboundPercentage_advanced,OPP_turnoverRatio_advanced,OPP_effectiveFieldGoalPercentage_advanced,OPP_trueShootingPercentage_advanced,OPP_usagePercentage_advanced,OPP_estimatedPace_advanced,OPP_pace_advanced,OPP_possessions_advanced,OPP_PIE_advanced,OPP_effectiveFieldGoalPercentage_fourfactors,OPP_freeThrowAttemptRate_fourfactors,OPP_teamTurnoverPercentage_fourfactors,OPP_oppEffectiveFieldGoalPercentage_fourfactors,OPP_oppFreeThrowAttemptRate_fourfactors,OPP_oppTeamTurnoverPercentage_fourfactors,OPP_oppOffensiveReboundPercentage_fourfactors,OPP_foulsDrawn_misc,OPP_percentageFieldGoalsAttempted2pt_scoring,OPP_percentageFieldGoalsAttempted3pt_scoring,OPP_percentagePoints2pt_scoring,OPP_percentagePointsMidrange2pt_scoring,OPP_percentagePoints3pt_scoring,OPP_percentagePointsFastBreak_scoring,OPP_percentagePointsFreeThrow_scoring,OPP_percentagePointsOffTurnovers_scoring,OPP_percentagePointsPaint_scoring,OPP_percentageAssisted2pt_scoring,OPP_percentageUnassisted2pt_scoring,OPP_percentageAssisted3pt_scoring,OPP_percentageUnassisted3pt_scoring,OPP_percentageAssistedFGM_scoring,OPP_percentageUnassistedFGM_scoring,OPP_threePointersPercentage_traditional,OPP_freeThrowsPercentage_traditional,OPP_percentageFieldGoalsMade_usage,OPP_percentageFieldGoalsAttempted_usage,OPP_percentageThreePointersMade_usage,OPP_percentageThreePointersAttempted_usage,OPP_percentageFreeThrowsMade_usage,OPP_percentageFreeThrowsAttempted_usage,OPP_percentageReboundsOffensive_usage,OPP_percentageReboundsDefensive_usage,OPP_percentageReboundsTotal_usage,OPP_percentageAssists_usage,OPP_percentageTurnovers_usage,OPP_percentageSteals_usage,OPP_percentageBlocks_usage,OPP_percentageBlocksAllowed_usage,OPP_percentagePersonalFouls_usage,OPP_percentagePersonalFoulsDrawn_usage,OPP_percentagePoints_usage,OPP_plusMinusPoints_traditional,MATCHUP,SEASON,TEAM_NAME,OPPONENT_NAME,num_absent_other,num_injured,num_personal,num_present,num_resting,num_suspended,player_perf_score_mean,player_perf_score_sum,top_player_absent_other,top_player_absent_other_rate,top_player_absent_rate,top_player_count,top_player_injured,top_player_injury_rate,top_player_personal,top_player_personal_rate,top_player_resting,top_player_resting_rate,top_player_suspended,top_player_suspension_rate,OPP_num_absent,OPP_num_injured,OPP_num_personal,OPP_num_present,OPP_num_resting,OPP_num_suspended,OPP_num_absent_other,OPP_player_perf_score_mean,OPP_player_perf_score_sum,OPP_top_player_absent,OPP_top_player_absent_rate,OPP_top_player_count,OPP_top_player_injured,OPP_top_player_injury_rate,OPP_top_player_personal,OPP_top_player_personal_rate,OPP_top_player_resting,OPP_top_player_resting_rate,OPP_top_player_suspended,OPP_top_player_suspension_rate,OPP_top_player_absent_other,OPP_top_player_absent_other_rate
0,0029900001,1999-11-02,1610612739,1610612752,0,0,-8.0,1,0,1,0,84,NaN,NaN,30,77,7,14,17,23,9,29,38,23,10,2,18,27,240.000000,16,18,5,18,10,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,32.0,74.0,6.0,15.0,22.0,27.0,9.0,35.0,44.0,17.0,10.0,10.0,15.0,23.0,92.0,240.000000,20.0,10.0,8.0,26.0,2.0,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,CLE @ NYK,1999-00,cleveland cavaliers,new york knicks,1,0,0,11,0,0,13.175000,158.1,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,1,0,0,11,0,0,1,13.175000,158.1,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
1,0029900001,1999-11-02,1610612752,1610612739,1,1,8.0,1,0,3,0,92,NaN,NaN,32,74,6,15,22,27,9,35,44,17,10,10,15,23,240.000000,20,10,8,26,2,98.132465,91.007410,7.138000,0.138091,0.660656,14.414340,0.041851,0.138519,0.093162,10.718486,0.452203,0.514103,0.189160,96.002022,92.999508,64.810208,0.118791,0.474730,0.370718,0.188443,0.435168,0.300185,0.195257,0.201355,0.111458,0.792252,0.207891,0.559252,0.275400,0.145694,0.068824,0.244220,0.273872,0.283893,0.315212,0.633954,0.327361,0.000000,0.457383,0.491784,0.196417,0.769640,0.200191,0.200648,0.163681,0.182519,0.189975,0.187079,0.165201,0.200395,0.197848,0.197485,0.156261,0.184727,0.226056,0.158403,0.199342,0.014650,0.198439,7.415139,30.0,77.0,7.0,14.0,17.0,23.0,9.0,29.0,38.0,23.0,10.0,2.0,18.0,27.0,84.0,240.000000,16.0,18.0,5.0,18.0,10.0,90.733681,97.737250,-6.988278,0.192753,1.411334,19.952389,0.033153,0.128447,0.079094,14.011125,0.416957,0.469768,0.196084,96.000410,93.500258,56.054375,0.086425,0.433493,0.298513,0.196031,0.474877,0.369961,0.189484,0.242580,0.207917,0.787322,0.201011,0.503678,0.296652,0.212107,0.053691,0.196500,0.169005,0.207026,0.704014,0.147931,0.206631,0.249897,0.632994,0.218950,0.251120,0.581979,0.198319,0.200823,0.169585,0.180783,0.199848,0.203016,0.163000,0.199473,0.199854,0.206976,0.180579,0.178215,0.148264,0.229443,0.194080,0.014335,0.196578,-4.233125,NYK vs. CLE,1999-00,new york knicks,cleveland cavaliers,3,0,0,9,0,0,14.608333,175.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,3,0,0,9,0,0,3,14.608333,175.3,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
2,0029900002,1999-11-02,1610612751,1610612754,1,0,-7.0,1,1,2,1,112,NaN,NaN,36,81,5,12,35,46,15,30,45,11,11,4,18,39,240.000000,22,20,8,40,3,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,37.0,78.0,6.0,13.0,39.0,53.0,15.0,28.0,43.0,14.0,10.0,3.0,20.0,38.0,119.0,240.016667,19.0,25.0,12.0,42.0,4.0,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,NJN vs. IND,1999-00,brooklyn nets,indiana pacers,2,0,0,10,0,0,14.958333,179.5,1,0.2,0.2,5,0,0.0,0,0.0,0,0.0,0,0.0,2,0,0,10,0,0,2,14.958333,179.5,1,0.2,5,0,0.0,0,0.0,0,0.0,0,0.0,1,0.2
3,0029900002,1999-11-02,1610612754,1610612751,0,1,7.0,1,0,2,0,119,NaN,NaN,37,78,6,13,39,53,15,28,43,14,10,3,20,38,240.016667,19,25,12,42,4,111.010916,103.199708,7.811208,0.090626,0.519961,10.650885,0.066723,0.114252,0.089925,15.337539,0.537174,0.590935,0.197836,105.280436,108.000458,61.738560,0.095848,0.514629,0.691705,0.187933,0.476372,0.568241,0.171832,0.344928,0.455871,0.826516,0.173484,0.526269,0.173445,0.170067,0.083064,0.256120,0.138516,0.352695,0.269519,0.682915,0.469967,0.048191,0.365172,0.587262,0.442511,0.575040,0.197908,0.200782,0.208183,0.179729,0.185648,0.185818,0.203955,0.199004,0.197018,0.209140,0.200613,0.186442,0.192869,0.160660,0.196291,0.014945,0.198406,5.461426,36.0,81.0,5.0,12.0,35.0,46.0,15.0,30.0,45.0,11.0,11.0,4.0,18.0,39.0,112.0,240.000000,22.0,20.0,8.0,40.0,3.0,103.037021,110.423160,-7.397125,0.093954,0.374306,7.795562,0.063256,0.127267,0.094153,11.500326,0.544179,0.589837,0.193948,105.281281,108.500828,67.433611,0.095616,0.475948,0.565859,0.172617,0.513612,0.687339,0.187842,0.338847,0.368264,0.838005,0.138940,0.548426,0.211650,0.108675,0.104131,0.319844,0.193684,0.336908,0.307333,0.524681,0.073889,0.264792,0.380447,0.596498,0.128292,0.702157,0.200503,0.203035,0.129688,0.171099,0.198261,0.193761,0.199947,0.203550,0.199933,0.212605,0.187613,0.189531,0.155583,0.146405,0.196895,0.014148,0.198515,-5.470972,IND @ NJN,1999-00,indiana pacers,brooklyn nets,2,0,0,10,0,0,15.383333,184.6,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,2,0,0,10,0,0,2,15.383333,184.6,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
4,0029900003,1999-11-02,1610612737,1610612764,0,0,-7.0,1,1,2,1,87,NaN,NaN,31,78,2,6,23,30,16,34,50,15,5,5,23,22,240.000000,14,10,14,32,5,89.259479,96.353313,-7.075097,0.127295,0.373726,9.903090,0.064874,0.139126,0.101001,16.693944,0.410884,0.479125,0.200495,98.118501,97.600537,61.293611,0.088329,0.414216,0.401616,0.233748,0.462236,0.185940,0.152675,0.265121,0.503056,0.929368,0.070787,0.714106,0.256272,0.048078,0.153771,0.237661,0.150749,0.457861,0.421989,0.532872,0.000000,0.199514,0.405471,0.594529,0.176944,0.572303,0.202958,0.200886,0.099757,0.222895,0.177422,0.184213,0.191125,0.212502,0.204615,0.215720,0.207392,0.174378,0.154861,0.150347,0.181666,0.028054,0.201412,-2.602917,39.0,88.0,3.0,10.0,13.0,16.0,12.0,30.0,42.0,23.0,5.0,5.0,15.0,30.0,94.0,240.000000,21.0,13.0,6.0,40.0,5.0,95.607153,87.699611,7.902674,0.142049,0.605174,20.307479,0.046938,0.118369,0.083026,10.285243,0.505227,0.527368,0.195427,98.120797,98.500015,46.877917,0.105983,0.461744,0.185739,0.153030,0.408839,0.400769,0.234769,0.346544,0.702847,0.878051,0.090977,0.792576,0.317607,0.079125,0.079987,0.097327,0.239451,0.474969,0.487619,0.481409,0.131875,0.000000,0.564075,0.404953,0.054433,0.349670,0.204716,0.200208,0.085926,0.136903,0.190875,0.203007,0.185406,0.196825,0.197388,0.189788,0.200875,0.185517,0.172653,0.155711,0.199349,0.080037,0.204833,4.042986,ATL @ WAS,1999-00,atlanta hawks,washington wizards,1,0,1,10,0,0,13.041667,156.5,0,0.0,0.2,5,0,0.0,1,0.2,0,0.0,0,0.0,2,0,1,10,0,0,1,13.041667,156.5,1,0.2,5,0,0.0,1,0.2,0,0.0,0,0.0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66196,0042400401,2025-06-05,1610612760,1610612754,1,0,-1.0,1,0,3,0,110,NaN,NaN,39,98,11,30,21,24,10,29,39,13,14,6,6,19,240.016667,11,11,11,46,7,104.859211,107.238254,-2.401319,0.089877,0.484480,9.231408,0.032102,0.126582,0.073159,4.215554,0.471415,0.518615,0.190986,104.398813,104.097747,65.037497,0.097399,0.455725,0.253861,0.066125,0.585600,0.256203,0.242994,0.305840,2.829040,0.638792,0.358499,0.523928,0.053338,0.277455,0.101775,0.178516,0.108151,0.470590,0.280170,0.548314,0.341042,0.292109,0.451021,0.528911,0.280632,0.579554,0.197089,0.199259,0.183445,0.203555,0.203944,0.205643,0.158191,0.195664,0.189841,0.191115,0.166873,0.207506,0.252223,0.156445,0.205720,0.204903,0.201040,-1.280814,39.0,82.0,18.0,39.0,15.0,21.0,13.0,43.0,56.0,24.0,1.0,7.0,24.0,22.0,111.0,240.016667,4.0,12.0,10.0,34.0,6.0,107.199743,106.020887,1.185473,0.152824,1.487171,16.042157,0.054027,0.135550,0.102712,16.549691,0.590604,0.622814,0.194014,104.398840,103.499456,61.453580,0.105077,0.587677,0.257399,0.241239,0.456693,0.248252,0.066348,0.198115,2.300604,0.501280,0.498720,0.367759,0.077094,0.487458,0.102077,0.145064,0.030612,0.290827,0.311811,0.520492,0.785258,0.148566,0.577500,0.422500,0.453506,0.406064,0.201986,0.200134,0.195214,0.196461,0.208137,0.204329,0.181644,0.190189,0.193941,0.198113,0.190323,0.068954,0.205017,0.172056,0.188080,0.209822,0.200037,3.767655,OKC vs. IND,2024-25,oklahoma city thunder,indiana pacers,3,0,0,11,0,0,13.592857,190.3,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,3,0,0,11,0,0,3,13.592857,190.3,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
66197,0042400402,2025-06-08,1610612754,1610612760,0,0,-16.0,1,0,3,0,107,NaN,NaN,37,82,14,40,19,26,7,28,35,27,9,6,15,25,240.000000,17,10,9,34,4,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,40.0,82.0,14.0,36.0,29.0,33.0,11.0,32.0,43.0,25.0,10.0,4.0,13.0,20.0,123.0,240.000000,14.0,9.0,4.0,42.0,6.0,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,IND @ OKC,2024-25,indiana pacers,oklahoma city thunder,1,2,0,12,0,0,12.633333,189.5,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,3,2,0,12,0,0,1,12.633333,189.5,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0
66198,0042400402,2025-06-08,1610612760,1610612754,1,1,16.0,0,0,0,0,123,NaN,NaN,40,82,14,36,29,33,11,32,43,25,10,4,13,20,240.000000,14,9,4,42,6,124.927028,107.611965,17.327417,0.165791,1.589896,19.668556,0.045791,0.133632,0.092358,8.651090,0.527407,0.586091,0.195107,100.478826,99.098391,52.651944,0.117421,0.604591,0.467545,0.142374,0.534502,0.319897,0.148433,0.177770,3.164306,0.531637,0.440447,0.440503,0.056893,0.317947,0.026094,0.193078,0.072515,0.383494,0.519340,0.300729,0.709903,0.017111,0.669727,0.270551,0.261287,0.592896,0.201530,0.204388,0.214924,0.203669,0.203131,0.202932,0.187598,0.194976,0.194408,0.207842,0.195114,0.183332,0.142664,0.136569,0.179131,0.218797,0.199623,7.487847,37.0,82.0,14.0,40.0,19.0,26.0,7.0,28.0,35.0,27.0,9.0,6.0,15.0,25.0,107.0,240.000000,17.0,10.0,9.0,34.0,4.0,107.749493,125.240944,-17.504944,0.192788,1.313061,17.297743,0.028622,0.128916,0.075563,10.674743,0.518804,0.563388,0.192446,100.480918,98.800358,51.636806,0.083734,0.537393,0.318106,0.147637,0.584459,0.455280,0.141166,0.278398,2.256319,0.473365,0.509969,0.365112,0.100213,0.425986,0.073556,0.192350,0.172364,0.264890,0.556698,0.242607,0.876344,0.047545,0.732554,0.202584,0.359288,0.351443,0.200187,0.200804,0.212136,0.203101,0.213007,0.211989,0.193367,0.198466,0.201860,0.192983,0.190133,0.199179,0.187639,0.111100,0.193683,0.196846,0.201050,-8.625486,OKC vs. IND,2024-25,oklahoma city thunder,indiana pacers,0,0,0,14,0,0,15.221429,213.1,0,0.0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0,0,14,0,0,0,15.221429,213.1,0,0.0,5,0,0.0,0,0.0,0,0.0,0,0.0,0,0.0

# 🚀 Features avancées

In [ ]:

# Ajouter les features avancées aux stats de match
#match_dataset = add_advanced_boxscore_features(match_dataset)

# MOVED TO CONFIG
# features_to_roll = cols_to_sum + cols_to_weighted_avg
# features_to_roll += [f"OPP_{col}" for col in cols_to_sum + cols_to_weighted_avg]

# Calcul des features glissantes shiftées
match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], features_to_roll, N_LIST, method="ewm")

match_dataset = compute_rolling_features(match_dataset, "TEAM_ID", ["TEAM_ID", "GAME_DATE"], top_player_features_to_roll, N_LIST_TOP, method="ewm", apply_log=True)


match_dataset = compute_winrates(match_dataset, "TEAM_ID", "IS_WIN", "IS_HOME", N_LIST)
match_dataset = compute_win_ratio(match_dataset, "TEAM_ID", "IS_WIN", N_LIST)

match_dataset["IS_WIN_SHIFTED"] = match_dataset.groupby("TEAM_ID")["IS_WIN"].shift(1).fillna(0).astype(int)
match_dataset["WIN_STREAK"] = match_dataset.groupby("TEAM_ID").apply(
    lambda x: compute_win_streak(x, "TEAM_ID", "IS_WIN_SHIFTED")).reset_index(level=0, drop=True)
match_dataset = compute_side_win_streak(match_dataset, win_shifted_col="IS_WIN_SHIFTED")


# Calcul des jours de repos pour l'équipe et l'adversaire
match_dataset["DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "TEAM_ID")
match_dataset["OPP_DAYS_SINCE_LAST_GAME"] = compute_rest_days(match_dataset, "GAME_DATE", "OPP_TEAM_ID")

# Avantage de repos
match_dataset["REST_ADVANTAGE"] = (
    match_dataset["DAYS_SINCE_LAST_GAME"] - match_dataset["OPP_DAYS_SINCE_LAST_GAME"]
)


match_dataset = compute_rolling_rest_advantage(
    match_dataset, "TEAM_ID", "IS_HOME", "REST_ADVANTAGE", N_LIST
)

match_dataset = compute_home_away_pts(
    match_dataset, "TEAM_ID", "IS_HOME", "points_traditional", "OPP_points_traditional", N_LIST
)

# match_dataset = rename_pts_against_columns(match_dataset)

match_dataset = compute_h2h(match_dataset, N_LIST)
# match_dataset = compute_h2h_pts_margin(match_dataset, N_LIST)
match_dataset = compute_h2h_season(match_dataset)
match_dataset = compute_h2h_streak(match_dataset)

match_dataset = compute_elo(match_dataset)
match_dataset = compute_elo_season(match_dataset)

match_dataset = convert_elos_to_elo_diff(match_dataset)

/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (
/home/ju/Documents/Dev/Python/NBA_Predictor/src/feature_builder.py:35: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[roll_col] = (

In [ ]:
pd.options.display.max_columns = None
display(match_dataset)

          GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      0029900001 1999-11-02  1610612739  1610612752        0       0
1      0029900001 1999-11-02  1610612752  1610612739        1       1
2      0029900002 1999-11-02  1610612751  1610612754        1       0
3      0029900002 1999-11-02  1610612754  1610612751        0       1
4      0029900003 1999-11-02  1610612737  1610612764        0       0
...           ...        ...         ...         ...      ...     ...
66196  0042400401 2025-06-05  1610612760  1610612754        1       0
66197  0042400402 2025-06-08  1610612754  1610612760        0       0
66198  0042400402 2025-06-08  1610612760  1610612754        1       1
66199  0042400403 2025-06-11  1610612754  1610612760        1       1
66200  0042400403 2025-06-11  1610612760  1610612754        0       0

       POINT_DIFF  has_absent  has_top_absent  num_absent  top_player_absent  \
0            -8.0           1               0           1                  0
1             8.0           1               0           3                  0
2            -7.0           1               1           2                  1
3             7.0           1               0           2                  0
4            -7.0           1               1           2                  1
...           ...         ...             ...         ...                ...
66196        -1.0           1               0           3                  0
66197       -16.0           1               0           3                  0
66198        16.0           0               0           0                  0
66199         9.0           1               0           5                  0
66200        -9.0           1               0           3                  0

       points_traditional  ODDS  OPP_ODDS  fieldGoalsMade_traditional  \
0                      84   NaN       NaN                          30
1                      92   NaN       NaN                          32
2                     112   NaN       NaN                          36
3                     119   NaN       NaN                          37
4                      87   NaN       NaN                          31
...                   ...   ...       ...                         ...
66196                 110   NaN       NaN                          39
66197                 107   NaN       NaN                          37
66198                 123   NaN       NaN                          40
66199                 116   NaN       NaN                          44
66200                 107   NaN       NaN                          37

       fieldGoalsAttempted_traditional  threePointersMade_traditional  \
0                                   77                              7
1                                   74                              6
2                                   81                              5
3                                   78                              6
4                                   78                              2
...                                ...                            ...
66196                               98                             11
66197                               82                             14
66198                               82                             14
66199                               85                              9
66200                               79                             10

       threePointersAttempted_traditional  freeThrowsMade_traditional  \
0                                      14                          17
1                                      15                          22
2                                      12                          35
3                                      13                          39
4                                       6                          23
...                                   ...                         ...
66196                                  30                          21
66197                                  40                          19
66198                                  36                          29
66199                                  27                          19
66200                                  22                          23

       freeThrowsAttempted_traditional  reboundsOffensive_traditional  \
0                                   23                              9
1                                   27                              9
2                                   46                             15
3                                   53                             15
4                                   30                             16
...                                ...                            ...
66196                               24                             10
66197                               26                              7
66198                               33                             11
66199                               22                              7
66200                               30                              9

       reboundsDefensive_traditional  reboundsTotal_traditional  \
0                                 29                         38
1                                 35                         44
2                                 30                         45
3                                 28                         43
4                                 34                         50
...                              ...                        ...
66196                             29                         39
66197                             28                         35
66198                             32                         43
66199                             29                         36
66200                             33                         42

       assists_traditional  steals_traditional  blocks_traditional  \
0                       23                  10                   2
1                       17                  10                  10
2                       11                  11                   4
3                       14                  10                   3
4                       15                   5                   5
...                    ...                 ...                 ...
66196                   13                  14                   6
66197                   27                   9                   6
66198                   25                  10                   4
66199                   24                  13                  11
66200                   16                   6                   4

       turnovers_traditional  foulsPersonal_traditional  MINUTES_PLAYED  \
0                         18                         27      240.000000
1                         15                         23      240.000000
2                         18                         39      240.000000
3                         20                         38      240.016667
4                         23                         22      240.000000
...                      ...                        ...             ...
66196                      6                         19      240.016667
66197                     15                         25      240.000000
66198                     13                         20      240.000000
66199                     13                         24      240.000000
66200                     17                         20      240.000000

       pointsOffTurnovers_misc  pointsSecondChance_misc  pointsFastBreak_misc  \
0                           16                       18                     5
1                           20                       10                     8
2                           22                       20                     8
3                           19                       25                    12
4                           14                       10                    14
...                        ...                      ...                   ...
66196                       11                       11                    11
66197                       17                       10                     9
66198                       14                        9                     4
66199                       21                       13                    17
66200                       14                        7                    10

       pointsPaint_misc  blocksAgainst_misc  offensiveRating_advanced  \
0                    18                  10                 90.733681
1                    26                   2                 98.132465
2                    40                   3                103.037021
3                    42                   4                111.010916
4                    32                   5                 89.259479
...                 ...                 ...                       ...
66196                46                   7                104.859211
66197                34                   4                107.749493
66198                42                   6                124.927028
66199                50                   4                114.081778
66200                48                  11                104.041729

       defensiveRating_advanced  netRating_advanced  \
0                     97.737250           -6.988278
1                     91.007410            7.138000
2                    110.423160           -7.397125
3                    103.199708            7.811208
4                     96.353313           -7.075097
...                         ...                 ...
66196                107.238254           -2.401319
66197                125.240944          -17.504944
66198                107.611965           17.327417
66199                103.844535           10.243340
66200                113.766938           -9.725208

       assistPercentage_advanced  assistToTurnover_advanced  \
0                       0.192753                   1.411334
1                       0.138091                   0.660656
2                       0.093954                   0.374306
3                       0.090626                   0.519961
4                       0.127295                   0.373726
...                          ...                        ...
66196                   0.089877                   0.484480
66197                   0.192788                   1.313061
66198                   0.165791                   1.589896
66199                   0.143614                   0.890670
66200                   0.109897                   1.188749

       assistRatio_advanced  offensiveReboundPercentage_advanced  \
0                 19.952389                             0.033153
1                 14.414340                             0.041851
2                  7.795562                             0.063256
3                 10.650885                             0.066723
4                  9.903090                             0.064874
...                     ...                                  ...
66196              9.231408                             0.032102
66197             17.297743                             0.028622
66198             19.668556                             0.045791
66199             13.519639                             0.032210
66200             12.576111                             0.040029

       defensiveReboundPercentage_advanced  reboundPercentage_advanced  \
0                                 0.128447                    0.079094
1                                 0.138519                    0.093162
2                                 0.127267                    0.094153
3                                 0.114252                    0.089925
4                                 0.139126                    0.101001
...                                    ...                         ...
66196                             0.126582                    0.073159
66197                             0.128916                    0.075563
66198                             0.133632                    0.092358
66199                             0.127237                    0.081195
66200                             0.148027                    0.094363

       turnoverRatio_advanced  effectiveFieldGoalPercentage_advanced  \
0                   14.011125                               0.416957
1                   10.718486                               0.452203
2                   11.500326                               0.544179
3                   15.337539                               0.537174
4                   16.693944                               0.410884
...                       ...                                    ...
66196                4.215554                               0.471415
66197               10.674743                               0.518804
66198                8.651090                               0.527407
66199               10.168583                               0.564719
66200               13.171382                               0.551383

       trueShootingPercentage_advanced  usagePercentage_advanced  \
0                             0.469768                  0.196084
1                             0.514103                  0.189160
2                             0.589837                  0.193948
3                             0.590935                  0.197836
4                             0.479125                  0.200495
...                                ...                       ...
66196                         0.518615                  0.190986
66197                         0.563388                  0.192446
66198                         0.586091                  0.195107
66199                         0.589556                  0.194711
66200                         0.595842                  0.188548

       estimatedPace_advanced  pace_advanced  possessions_advanced  \
0                   96.000410      93.500258             56.054375
1                   96.002022      92.999508             64.810208
2                  105.281281     108.500828             67.433611
3                  105.280436     108.000458             61.738560
4                   98.118501      97.600537             61.293611
...                       ...            ...                   ...
66196              104.398813     104.097747             65.037497
66197              100.480918      98.800358             51.636806
66198              100.478826      99.098391             52.651944
66199              101.940403     102.401259             58.636806
66200              101.939283     102.497244             68.000069

       PIE_advanced  effectiveFieldGoalPercentage_fourfactors  \
0          0.086425                                  0.433493
1          0.118791                                  0.474730
2          0.095616                                  0.475948
3          0.095848                                  0.514629
4          0.088329                                  0.414216
...             ...                                       ...
66196      0.097399                                  0.455725
66197      0.083734                                  0.537393
66198      0.117421                                  0.604591
66199      0.110640                                  0.569751
66200      0.090457                                  0.532462

       freeThrowAttemptRate_fourfactors  teamTurnoverPercentage_fourfactors  \
0                              0.298513                            0.196031
1                              0.370718                            0.188443
2                              0.565859                            0.172617
3                              0.691705                            0.187933
4                              0.401616                            0.233748
...                                 ...                                 ...
66196                          0.253861                            0.066125
66197                          0.318106                            0.147637
66198                          0.467545                            0.142374
66199                          0.258165                            0.138367
66200                          0.380398                            0.185438

       oppEffectiveFieldGoalPercentage_fourfactors  \
0                                         0.474877
1                                         0.435168
2                                         0.513612
3                                         0.476372
4                                         0.462236
...                                            ...
66196                                     0.585600
66197                                     0.584459
66198                                     0.534502
66199                                     0.532022
66200                                     0.571176

       oppFreeThrowAttemptRate_fourfactors  \
0                                 0.369961
1                                 0.300185
2                                 0.687339
3                                 0.568241
4                                 0.185940
...                                    ...
66196                             0.256203
66197                             0.455280
66198                             0.319897
66199                             0.386116
66200                             0.265022

       oppTeamTurnoverPercentage_fourfactors  \
0                                   0.189484
1                                   0.195257
2                                   0.187842
3                                   0.171832
4                                   0.152675
...                                      ...
66196                               0.242994
66197                               0.141166
66198                               0.148433
66199                               0.185964
66200                               0.137716

       oppOffensiveReboundPercentage_fourfactors  foulsDrawn_misc  \
0                                       0.242580         0.207917
1                                       0.201355         0.111458
2                                       0.338847         0.368264
3                                       0.344928         0.455871
4                                       0.265121         0.503056
...                                          ...              ...
66196                                   0.305840         2.829040
66197                                   0.278398         2.256319
66198                                   0.177770         3.164306
66199                                   0.233093         2.106042
66200                                   0.176117         3.636528

       percentageFieldGoalsAttempted2pt_scoring  \
0                                      0.787322
1                                      0.792252
2                                      0.838005
3                                      0.826516
4                                      0.929368
...                                         ...
66196                                  0.638792
66197                                  0.473365
66198                                  0.531637
66199                                  0.654474
66200                                  0.704326

       percentageFieldGoalsAttempted3pt_scoring  percentagePoints2pt_scoring  \
0                                      0.201011                     0.503678
1                                      0.207891                     0.559252
2                                      0.138940                     0.548426
3                                      0.173484                     0.526269
4                                      0.070787                     0.714106

# 🧽 Nettoyage et sauvegarde

In [ ]:

#TODO : see why not found in config.py after reboot
player_absent_input_cols = [
    'has_top_absent',
    'has_absent',
    'top_player_absent',
    'num_absent',
]

final_date = datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
raw_save_path = os.path.join(DATA_FINAL_DATASET_DIR, f'nba_features_final_{final_date}.csv')
clean_save_path = os.path.join(DATA_FINAL_CLEANED_DATASET_DIR, f'nba_features_cleaned_final_{final_date}.csv')

os.makedirs(DATA_FINAL_DATASET_DIR, exist_ok=True)
os.makedirs(DATA_FINAL_CLEANED_DATASET_DIR, exist_ok=True)

match_dataset.to_csv(raw_save_path, index=False)

cols_to_drop = features_to_roll+top_player_features_to_roll+COLS_MATCH_REAL
#remove num_absent and top_player_absent from cols_to_drop to see if we can use them has input
cols_to_drop = [col for col in cols_to_drop if col not in player_absent_input_cols]


final_cleaned = match_dataset.drop(columns=cols_to_drop, errors='ignore')
final_cleaned.to_csv(clean_save_path, index=False)

print(f"✅ Fichier brut : {raw_save_path}")
print(f"✅ Fichier clean : {clean_save_path}")

final_cleaned

✅ Fichier brut : data/final_dataset/nba_features_final_2025-06-18_18-06-14.csv
✅ Fichier clean : data/final_cleaned_dataset/nba_features_cleaned_final_2025-06-18_18-06-14.csv

          GAME_ID  GAME_DATE     TEAM_ID OPP_TEAM_ID  IS_HOME  IS_WIN  \
0      0029900001 1999-11-02  1610612739  1610612752        0       0
1      0029900001 1999-11-02  1610612752  1610612739        1       1
2      0029900002 1999-11-02  1610612751  1610612754        1       0
3      0029900002 1999-11-02  1610612754  1610612751        0       1
4      0029900003 1999-11-02  1610612737  1610612764        0       0
...           ...        ...         ...         ...      ...     ...
66196  0042400401 2025-06-05  1610612760  1610612754        1       0
66197  0042400402 2025-06-08  1610612754  1610612760        0       0
66198  0042400402 2025-06-08  1610612760  1610612754        1       1
66199  0042400403 2025-06-11  1610612754  1610612760        1       1
66200  0042400403 2025-06-11  1610612760  1610612754        0       0

       POINT_DIFF  has_absent  has_top_absent  num_absent  top_player_absent  \
0            -8.0           1               0           1                  0
1             8.0           1               0           3                  0
2            -7.0           1               1           2                  1
3             7.0           1               0           2                  0
4            -7.0           1               1           2                  1
...           ...         ...             ...         ...                ...
66196        -1.0           1               0           3                  0
66197       -16.0           1               0           3                  0
66198        16.0           0               0           0                  0
66199         9.0           1               0           5                  0
66200        -9.0           1               0           3                  0

       ODDS  OPP_ODDS   SEASON  ROLL_fieldGoalsMade_traditional_3  \
0       NaN       NaN  1999-00                                NaN
1       NaN       NaN  1999-00                                NaN
2       NaN       NaN  1999-00                                NaN
3       NaN       NaN  1999-00                                NaN
4       NaN       NaN  1999-00                                NaN
...     ...       ...      ...                                ...
66196   NaN       NaN  2024-25                          44.843719
66197   NaN       NaN  2024-25                          40.028400
66198   NaN       NaN  2024-25                          41.921860
66199   NaN       NaN  2024-25                          38.514200
66200   NaN       NaN  2024-25                          40.960930

       ROLL_fieldGoalsMade_traditional_5  ROLL_fieldGoalsMade_traditional_10  \
0                                    NaN                                 NaN
1                                    NaN                                 NaN
2                                    NaN                                 NaN
3                                    NaN                                 NaN
4                                    NaN                                 NaN
...                                  ...                                 ...
66196                          43.983628                           43.278729
66197                          40.234179                           41.051584
66198                          42.322419                           42.500779
66199                          39.156119                           40.314932
66200                          41.548279                           42.046092

       ROLL_fieldGoalsMade_traditional_25  ROLL_fieldGoalsMade_traditional_50  \
0                                     NaN                                 NaN
1                                     NaN                                 NaN
2                                     NaN                                 NaN
3                                     NaN                                 NaN
4                                     NaN                                 NaN
...                                   ...                                 ...
66196                           43.625945                           44.133858
66197                           42.316952                           43.034113
66198                           43.270103                           43.932530
66199                           41.907956                           42.797481
66200                           43.018557                           43.778313

       ROLL_fieldGoalsMade_traditional_100  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
...                                    ...
66196                            44.182462
66197                            43.614627
66198                            44.079839
66199                            43.483644
66200                            43.999050

       ROLL_fieldGoalsMade_traditional_200  \
0                                      NaN
1                                      NaN
2                                      NaN
3                                      NaN
4                                      NaN
...                                    ...
66196                            43.714693
66197                            43.914029
66198                            43.667781
66199                            43.845232
66200                            43.631286

       ROLL_fieldGoalsAttempted_traditional_3  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
66196                               89.588805
66197                               82.148175
66198                               93.794403
66199                               82.074088
66200                               87.897201

       ROLL_fieldGoalsAttempted_traditional_5  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
66196                               89.641440
66197                               82.525417
66198                               92.427627
66199                               82.350278
66200                               88.951751

       ROLL_fieldGoalsAttempted_traditional_10  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
66196                                90.308633
66197                                83.942133
66198                                91.707063
66199                                83.589018
66200                                89.942143

       ROLL_fieldGoalsAttempted_traditional_25  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
66196                                91.736809
66197                                86.542144
66198                                92.218593
66199                                86.192748
66200                                91.432547

       ROLL_fieldGoalsAttempted_traditional_50  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN
...                                        ...
66196                                92.242700
66197                                87.949057
66198                                92.468476
66199                                87.715761
66200                                92.057948

       ROLL_fieldGoalsAttempted_traditional_100  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
66196                                 91.994157
66197                                 88.798977
66198                                 92.113085
66199                                 88.664344
66200                                 91.912826

       ROLL_fieldGoalsAttempted_traditional_200  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
...                                         ...
66196                                 91.362935
66197                                 89.427669
66198                                 91.428975
66199                                 89.353762
66200                                 91.335155

       ROLL_threePointersMade_traditional_3  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
66196                             14.018935
66197                             15.899141
66198                             12.509468
66199                             14.949571
66200                             13.254734

       ROLL_threePointersMade_traditional_5  \
0                                       NaN
1                                       NaN
2                                       NaN
3                                       NaN
4                                       NaN
...                                     ...
66196                             13.443191
66197                             14.691985
66198                             12.628794
66199                             14.461323
66200                             13.085863

       ROLL_threePointersMade_traditional_10  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
66196                              12.895852
66197                              13.785683
66198                              12.551152
66199                              13.824650
66200                              12.814579

       ROLL_threePointersMade_traditional_25  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
66196                              13.320431
66197                              13.597992
66198                              13.141937
66199                              13.628916
66200                              13.207941

       ROLL_threePointersMade_traditional_50  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN
...                                      ...
66196                              13.867328
66197                              13.573335
66198                              13.754884
66199                              13.590067
66200                              13.764496

       ROLL_threePointersMade_traditional_100  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
66196                               13.951766
66197                               13.379621
66198                               13.893315
66199                               13.391905
66200                               13.895427

       ROLL_threePointersMade_traditional_200  \
0                                         NaN
1                                         NaN
2                                         NaN
3                                         NaN
4                                         NaN
...                                       ...
66196                               13.597183
66197                               13.154876
66198                               13.571341
66199                               13.163285
66200                               13.575606

       ROLL_threePointersAttempted_traditional_3  \
0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
...                                          ...
66196                                  36.155626
66197                                  35.304658
66198                                  33.077813
66199                                  37.652329
66200                                  34.538907

       ROLL_threePointersAttempted_traditional_5  \
0                                            NaN
1                                            NaN
2                                            NaN
3                                            NaN
4                                            NaN
...                                          ...
66196                                  36.016307
66197                                  33.964295
66198                                  34.010871
66199                                  35.976196
66200                                  34.673914

       ROLL_threePointersAttempted_traditional_10  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
66196                                   36.211983
66197                                   33.375485
66198                                   35.082531
66199                                   34.579942
66200                                   35.249344

       ROLL_threePointersAttempted_traditional_25  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
66196                                   37.314425
66197                                   34.511861
66198                                   36.751777
66199                                   34.934025
66200                                   36.693948

       ROLL_threePointersAttempted_traditional_50  \
0                                             NaN
1                                             NaN
2                                             NaN
3                                             NaN
4                                             NaN
...                                           ...
66196                                   37.894891
66197                                   35.360605
66198                                   37.585287
66199                                   35.542542
66200                                   37.523119

       ROLL_threePointersAttempted_traditional_100  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN
...                                            ...
66196                                    37.721985
66197                                    35.424953
66198                                    37.569074
66199                                    35.515548
66200                                    37.538003

       ROLL_threePointersAttempted_traditional_200  \
0                                              NaN
1                                              NaN
2                                              NaN
3                                              NaN
4                                              NaN
...                                            ...
66196                                    36.889590
66197                                    35.210366
66198                                    36.821037
66199                                    35.258024
66200                                    36.812867

       ROLL_freeThrowsMade_traditional_3  ROLL_freeThrowsMade_traditional_5  \
0                                    NaN                                NaN
1                                    NaN                                NaN
2                                    NaN                                NaN
3                                    NaN                                NaN
4                                    NaN                                NaN
...                                  ...                                ...
66196                          17.494489                          17.632989
66197                          17.569568                          18.889723
66198                          19.247244                          18.755326
66199                          18.284784                          18.926482
66200                          24.123622                          22.170217

       ROLL_freeThrowsMade_traditional_10  ROLL_freeThrowsMade_traditional_25  \
0                                     NaN                                 NaN
1                                     NaN                                 NaN
2                                     NaN                                 NaN
3                                     NaN                                 NaN
4                                     NaN                                 NaN
...                                   ...                                 ...
66196                           18.055306                           18.274348
66197                           19.502615                           18.998266
66198                           18.590705                           18.484013
66199                           19.411231                           18.998399
66200                           20.483304                           19.292935

       ROLL_freeThrowsMade_traditional_50  \
0                                     NaN
1                                     NaN
2                                     NaN
3                                     NaN
4                                     NaN
...                                   ...
66196                           17.977009
66197                           18.259439
66198                           18.095558
66199                           18.288481
66200                           18.523183

       ROLL_freeThrowsMade_traditional_100  \
0                                      NaN
1                                      NaN

In [ ]:
final_cleaned.columns

Index(['GAME_ID', 'GAME_DATE', 'TEAM_ID', 'OPP_TEAM_ID', 'IS_HOME', 'IS_WIN',
       'POINT_DIFF', 'has_absent', 'has_top_absent', 'num_absent',
       ...
       'H2H_LAST_100_COUNT', 'H2H_LAST_200_DIFF', 'H2H_LAST_200_WINRATE',
       'H2H_LAST_200_COUNT', 'H2H_SEASON_WINS', 'H2H_SEASON_MATCHES',
       'H2H_SEASON_WINRATE', 'H2H_WIN_STREAK', 'ELO_DIFF', 'ELO_DIFF_SEASON'],
      dtype='object', length=1464)

In [ ]:
#store end time of notebook
end_time = datetime.now()
print("End time: ", end_time)
print("Total time: ", end_time - start_time)

End time:  2025-06-18 18:14:18.253294
Total time:  0:20:51.035422